### ISSUE TITLE
No cleanup after the key is deleted from definition

### ISSUE THREAD

**Issue by ilya-spv** [SparebankenVest/azure-key-vault-to-kubernetes#10]
Initial state:
A secret definition that works so that there is an AzureKeyVaultSecret and an ordinary secret in kuberentes created by the controller and synchronization happens.

Next state:
The AzureKeyVaultSecret definition is removed (in my case I changed name actually, so maybe that has to do something with it), changes are applied to kubernetes.

Outcome:
Both the old AzureKeyVaultSecret and Kubernetes secret is present in the culster.

Desired outcome:
Only the secrets defined in the configuration file should be present, both old resources have to be deleted.

**Comment by torresdal** [comment]
This issue been here a while now, not getting much attention. Though I believe you are correct - the consequences are low and the complexity for a fully working solution is high. I’m closing this for now, but if anyone have a pr with a good solution laying around, please reopen.
