### ISSUE TITLE
[FEATURE] Be able to pass metadata to Kubernetes Secrets when generated by AzureKeyVaultSecret

### ISSUE THREAD

**Issue by severity1** [SparebankenVest/azure-key-vault-to-kubernetes#104]
**Is your feature request related to a problem? Please describe.**
I am using tools that can automatically discover kubernetes secrets based on metadata labels and annotations. 

**Describe the solution you'd like**
I want to be able to pass annotations and labels to the Secret resource through AzureKeyVaultSecret so that my other automation tools can discover them.

**Describe alternatives you've considered**
patching the generated kubernetes secrets with the desired annotations and secrets after AzureKeyVaultSecret has generated them.

**Comment by torresdal** [comment]
Agree @severity1 - we'll try to add this to the upcoming 1.1 version.

**Comment by torresdal** [comment]
@severity1 this is now implemented in v1.1.0 - forward any labels and annotations from AzureKeyVaultSecret to Kubernetes Secret.

**Comment by severity1** [comment]
@torresdal thanks!
