### ISSUE TITLE
[BUG] Cannot use "System-assigned managed identity"

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [SparebankenVest/azure-key-vault-to-kubernetes#106]
**Describe the bug**
I get the following error when using the  Azure Key Vault Controller 

`
Application with identifier 'msi' was not found in the directory '86j44353-4gr4-6dfd-7j1s-4g5k1572h24s. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
`

I think it is due to the fact that I'm using System-assigned managed identity for AKS. 

**To Reproduce**
Create a AKS cluster with "System-assigned managed identity" and go through the tutorial.

**Expected behavior**

I would expect this to work even though I was using "System-assigned managed identity" in the same way as in 
 [secrets-store-csi-driver-provider-azure]( https://github.com/Azure/secrets-store-csi-driver-provider-azure )
where there is the option to use [System-assigned managed identity]( https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/user-assigned-msi-mode.md)

**Logs**
`
Application with identifier 'msi' was not found in the directory '86j44353-4gr4-6dfd-7j1s-4g5k1572h24s. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
`

**Comment by torresdal** [comment]
@thomasfrederikhoeck Should now work with latest beta. Would be great if you could verify. The official 1.1.0 version will go out as soon as the community have had time to verify the beta. 

Helm chart version `1.1.0-beta.28` for env-injector.
Helm chart version `1.1.0-beta.5`for controller.

E.g. install the env-injector like this:
```
helm install --upgrade azure-key-vault-env-injector \
  spv-charts/azure-key-vault-env-injector \
  --set installCrd=false \
  --namespace akv2k8s
  --version 1.1.0-beta.26
```

If you don't provide `--version`, helm will use latest stabel which is 1.0.2.

**Comment by torresdal** [comment]
Verified in cluster with system-assigned mi.

**Comment by thomasfrederikhoeck** [comment]
I can confirm it works. :-)

**Comment by bpoudel1210** [comment]
@thomasfrederikhoeck I am also trying to implement "System assigned managed identity". It looks like it will create multiple MI. Which MI should we use? 

Currently I am getting below error:
error: adal: Refresh request failed. Status Code = '403'. Response body: no AzureAssignedIdentity found for pod:xxxx in assigned state\n, requeuing"

**Comment by thomasfrederikhoeck** [comment]
Creating MIs? Isn't it just meant to use the existing? I'm far from an expert on this but it might help with a more detailed description on how you produce it this error 😊

**Comment by bpoudel1210** [comment]
In my case, Key-vault-controller pod was not able to connect to the azure key vault. To fix this I end up installing [mic-exception](https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/mic-exception.yaml)  and configured [AzurePodIdentityException](https://github.com/Azure/aad-pod-identity/blob/master/examples/azurepodidentityexception.yaml).
@thomasfrederikhoeck Thank you for your quick response!
