### ISSUE TITLE
[FEATURE] option not to base64 encode secret when reading from keyvault

### ISSUE THREAD

**Issue by mcwienczek** [SparebankenVest/azure-key-vault-to-kubernetes#109]
**Is your feature request related to a problem? Please describe.**

Right now all the secrets are base64 encoded when injected into Kubernetes secret. However, sometimes we need to store keys in keyvault as base64 values already. This means that the resulting kubernetes secret will be base64 encoded twice. The example is SSH keys. We need to store them in keyvault as base64 encoded values, and when they are read by akv2k8s, they are again base64 encoded.

**Describe the solution you'd like**
Add a parameter that defines that the secret is already base64 encoded and doesn't need to be encoded again.

**Describe alternatives you've considered**
No alernatives found so far.

**Additional context**

**Comment by torresdal** [comment]
This should be supported in 1.2-beta (at least) - by using transforms: https://akv2k8s.io/v1.2-beta/reference/azure-key-vault-secret/

As for the secret being base64 encoded, that is how Kubernetes secret's work - and out of akv2k8s control. By using transforms though, you can decode the base64 string from AKV before it gets encoded by Kubernetes in the Secret.

**Comment by mcwienczek-rtl** [comment]
This is really helpful. Thank you very much!

**Comment by mcwienczek** [comment]
This is really helpful! Thank you very much for help!

**Comment by torresdal** [comment]
It just took 6 months - sorry about that 🤦

**Comment by mcwienczek** [comment]
I understand that this is open source product and that you might be working on that in you spare time. I really appreciate your effort! I have been using akv2k8s for the last year and it has saved us from syncing secrets manually from Azure Keyvault. Really appreciate all the effort!
