### ISSUE TITLE
[Question] Is the use of managed identities in the AKS cluster supported?

### ISSUE THREAD

**Issue by hbiarge** [SparebankenVest/azure-key-vault-to-kubernetes#110]
**Your question**
I have an AKS cluster configured to use Managed Identities. I´ve installed the controller, but I have authentication errors trying to access the KeyVault. I´ve created an access policy in the KeyVault for the cluster System Assigned Identity and for the User Assigned Identity for the nodepool

**Logs**
time="2020-08-25T11:54:31Z" level=error msg="failed to get secret value for 'namespace/certificate-sync' from Azure Key vault 'KV-NAME' using object name 'CERT-NAME', error: failed to get certificate from azure key vault, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://KV-NAME.vault.azure.net/certificates/CERT-NAME/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"unauthorized_client\",\"error_description\":\"AADSTS700016: Application with identifier 'msi' was not found in the directory 'directory'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\\r\\nTrace ID: 496d5a65-988f-4637-86d4-cbdbd58d5800\\r\\nCorrelation ID: c1140475-7157-4291-960a-af75aeb5f06e\\r\\nTimestamp: 2020-08-25 11:54:31Z\",\"error_codes\":[700016],\"timestamp\":\"2020-08-25 11:54:31Z\",\"trace_id\":\"496d5a65-988f-4637-86d4-cbdbd58d5800\",\"correlation_id\":\"c1140475-7157-4291-960a-af75aeb5f06e\",\"error_uri\":\"https://login.microsoftonline.com/error?code=700016\"}"
time="2020-08-25T11:54:31Z" level=error msg="error syncing 'namespace/certificate-sync': Failed to get secret for 'certificate-sync' from Azure Key Vault 'KV-NAME', requeuing"

**Comment by torresdal** [comment]
Hi @hbiarge - we've added support for aks managed identies in a beta version (1.1.0-beta.38), but we're currently in the process of tweaking an verifying this 1.1 release. If you want to try the beta, and help us verify aks managed identities, use azure-key-vault-env-injector chart version `1.1.0-beta.22` and set 

```
image.tag=1.1.0-beta.38   
envImage.tag=1.1.0-beta.38 
caBundleController.image.tag=1.1.0-beta.35
```

**Comment by hbiarge** [comment]
Hi @torresdal,
Thanks for your response and for your work in this great project!
As I have AAD Pod Identity deployed in the cluster, I´ve switched to use a user managed identity and it works as a charm.

But I will try to help as much as I can with the test of the beta version and the support of AKS clusters with Managed Identities. I´ll post here any issue I can find.
