### ISSUE TITLE
[Question] Using `<image>@sha256:<sha>` image notation

### ISSUE THREAD

**Issue by marko-k0** [SparebankenVest/azure-key-vault-to-kubernetes#118]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Your question**
Using `<image>@sha256:<sha>` notation for image gives us error listed under Logs. We're still using verion 0.1.14 but we get the same error with 1.0.2. Is this notation supported? If we use tag notation, we don't have this problem.

**To Reproduce**
Use notation mentioned in the question for deployment with some env variable that you want to inject.

**Logs**
`2020/09/03 10:42:28 [ERROR] admission webhook error: failed to get auto cmd, error: failed to inspect docker image '<acr>.azurecr.io/<repo>/<image>@sha256:08944c7e72de10c451fec22da80e42775591fa573e632b4a89338e21eee98377', error: context deadline exceeded
`

**Comment by ChaosGramer** [comment]
Shirt question which version of aks / k8s are you running? 

Which Helm Chart version was used to install 1.0.2?

**Comment by marko-k0** [comment]
> Shirt question which version of aks / k8s are you running?
> 
> Which Helm Chart version was used to install 1.0.2?

AKS 1.15.11. We used Helm Chart version 1.0.2 with App version 1.0.2.

**Comment by torresdal** [comment]
@marko-k0 I believe version 1.0.2 does not support this. The latest 1.1 version does, as verified by this test: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/f08358e423db243188854db7badf7a205fe6c89d/cmd/azure-keyvault-secrets-webhook/registry_test.go#L43
