### ISSUE TITLE
[Question] Compatibility with Google distroless images

### ISSUE THREAD

**Issue by vsandeeppolavarapu** [SparebankenVest/azure-key-vault-to-kubernetes#120]
From initial analysis it looks like the mutating webhook uses a shell to copy/stage assets.

https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/cmd/azure-keyvault-secrets-webhook/pod.go#L49 

In Google distroless images, sh is actually not available. Wondering if you have plans on supporting these images (some alternatives to this are using alpine or the debug versions of distroless images which has busybox).

**Comment by torresdal** [comment]
Hi @vsandeeppolavarapu. The copy section of the mutating webhook you're referring to happens in the init-container, which is controlled by the env-injector and have its own image. You could still run a distroless image in your pod and that should work. The init-container only copies the env-injector executable into the pod volume, accessable to any container. Or are you asking if the env-injector init-container could be made distroless?
