### ISSUE TITLE
Can we see the secret value when using inject-secret option?

### ISSUE THREAD

**Issue by zaidmohd** [SparebankenVest/azure-key-vault-to-kubernetes#124]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Your question**
A clear and concise question.

**To Reproduce**
If question relates to a certain behavior, describe steps to reproduce:

**Logs**
If applicable, add logs to help add context to your question.

**Additional context**
Add any other context about the question here.

**Comment by torresdal** [comment]
From the docs:

>The end result is that all secrets gets injected transparently in-memory during container startup. It will not reveal any secret content in the container spec, disk or logs. The only component that can read the secrets, are the program running inside the container.

https://akv2k8s.io/how-it-works/#the-env-injector

**Comment by zaidmohd** [comment]
@torresdal Thanks for the quick response. If I depoy this pod (https://akv2k8s.io/tutorials/env-injection/1-secret/), can i see the secret in container logs?
Issue is: We are able to sync the secret and mount the secret. But if we try to inject the secret, the application breaks, so I was trying to see if I can validate it in some way.

**Comment by zaidmohd** [comment]
Traceback (most recent call last):
  File "scheduler_service.py", line 35, in <module>
    myclient = pymongo.MongoClient(mongo_url)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", line 524, in __init__
    res = uri_parser.parse_uri(entity, port, warn=True)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/uri_parser.py", line 346, in parse_uri
    user, passwd = parse_userinfo(userinfo)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/uri_parser.py", line 64, in parse_userinfo
    "RFC 3986, use %s()." % quote_fn)
pymongo.errors.InvalidURI: Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus().

**Comment by torresdal** [comment]
The only way (for security reasons) to output the secret, is for your application to output it in the logs. 

The other thing you can do, to see the value of the secret from AKV, is use the test container image we've created: spvest/akv2k8s-env-test:2.0.1 - see usage example here: https://akv2k8s.io/tutorials/env-injection/1-secret/

**Comment by zaidmohd** [comment]
Getting below error in the injector pod

time="2020-09-22T07:55:21Z" level=info msg="found pod to mutate in namespace 'abcd-namespace'"
time="2020-09-22T07:55:21Z" level=info msg="found container 'abcdcontainer' to mutate"
time="2020-09-22T07:55:21Z" level=info msg="checking for env vars containing '@azurekeyvault' in container abcdcontainer"
time="2020-09-22T07:55:21Z" level=info msg="found env var: user-inject@azurekeyvault"
time="2020-09-22T07:55:21Z" level=info msg="found env var: pwd-inject@azurekeyvault"
time="2020-09-22T07:55:21Z" level=info msg="did not find credentials to use with registry 'abcdpocacr.azurecr.io' - getting default credentials"        
time="2020-09-22T07:55:21Z" level=info msg="failed to read azure.json to get default credentials, error: open /etc/kubernetes/azure.json: no such file or directory"
time="2020-09-22T07:55:21Z" level=info msg="pulling docker image abcdpocacr.azurecr.io/raisrapifileserver:2020.3.4.3 to get entrypoint and cmd, timeout 
is 120 seconds"
2020/09/22 07:55:21 [ERROR] admission webhook error: failed to get auto cmd, error: failed to pull docker image 'abcdpocacr.azurecr.io/abcdcontainer:2020.3.4.3', error: Error response from daemon: Get https://abcdpocacr.azurecr.io/v2/abcdcontainer/manifests/2020.3.4.3: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.

**Comment by torresdal** [comment]
What version are you running? Chart and docker images?

**Comment by zaidmohd** [comment]
Azure AKS Private Cluster, using Pod Identity.

AKS 1.18.6
AKS2KV8 1.1.0

**Comment by torresdal** [comment]
Are you sure you're running akv2k8s 1.1.0? What's the image version of the init-container on your pod? Should be 1.1.0. Have you upgraded from a previous version of akv2k8s?

**Comment by zaidmohd** [comment]
Ok, Let me uninstall the controller and injecter releases and redeploy.

**Comment by zaidmohd** [comment]
The image version it shows is 1.0.2
spvest/azure-keyvault-controller:1.0.2
spvest/azure-keyvault-webhook:1.0.2
![image](https://user-images.githubusercontent.com/25724349/93869262-3087b100-fce9-11ea-8c78-fe8121987b94.png)

**Comment by zaidmohd** [comment]
Made some progress, and getting a different error when running the sample Pod you mentioned.

$ k logs akvs-secret-app-c5bcb6669-njr5c
time="2020-09-22T10:23:46Z" level=info msg="using sentralized akv2k8s auth service for authentiction with azure key vault" application=env-injector component=akv2k8s namespace=abcd-namespace
time="2020-09-22T10:23:46Z" level=info msg="found original container command to be /usr/local/bin/entrypoint.sh [entrypoint.sh TEST_SECRET]" application=env-injector component=akv2k8s namespace=abcd-namespace
time="2020-09-22T10:23:46Z" level=info msg="requesting azure key vault oauth token from https://azure-key-vault-env-injector.akv2k8s.svc:443/auth/abcd-namespace/akvs-secret-app-c5bcb6669-njr5c" application=env-injector component=akv2k8s namespace=abcd-namespace
time="2020-09-22T10:23:56Z" level=fatal msg="request token failed from https://azure-key-vault-env-injector.akv2k8s.svc:443/auth/abcd-namespace/akvs-secret-app-c5bcb6669-njr5c, error: Get https://azure-key-vault-env-injector.akv2k8s.svc:443/auth/abcd-namespace/akvs-secret-app-c5bcb6669-njr5c: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" application=env-injector component=akv2k8s namespace=abcd-namespace

**Comment by torresdal** [comment]
@zaidmohd Just to make sure we have the same base, have you installed akv2k8s in its own separate namespace (like `akv2k8s`)? I would also need to know any custom settings you passed on the the helm chart, if any.

Also, to be 100% sure you have a clean install (especially if you have used beta versions of akv2k8s previously):

1. Uninstall the helm chart
2. Delete the akv2k8s namespace
3. Install the halm chart

Then, you say you use aad-pod-identity - have a look in the docs and tell me which option you use: https://akv2k8s.io/security/authentication/#akv-authentication-with-the-env-injector

**Comment by zaidmohd** [comment]
@torresdal I followed and removed everything. And now Sync is also not working.

Env Details:
AKS 1.18.6 - Private cluster
aad pod identity 1.16.3 
akv2k8s 1.1 (Controller 1.1.0, Injector 1.1.5)

AAD Pod Identity Demp pod working as expected

Env Controller & Injector:
helm upgrade -i azure-key-vault-controller \
  spv-charts/azure-key-vault-controller \
  --namespace akv2k8s \
 --set keyVault.customAuth.enabled=true \
 --set keyVault.customAuth.podIdentitySelector="xxx-xxxx-xxx"
====================================
helm upgrade -i azure-key-vault-env-injector \
 spv-charts/azure-key-vault-env-injector \
 --namespace akv2k8s \
 --set keyVault.customAuth.enabled=true \
 --set keyVault.customAuth.podIdentitySelector="xxx-xxxx-xxx"

Error in Controller:
time="2020-09-23T16:19:44Z" level=error msg="failed to get secret value for 'abcd-namespace/zsecret-sync' from Azure Key vault 'abcd-kv-01' using object name 'abcduser', error: adal: Refresh request failed. Status Code = '404'. Response body: getting assigned identities for pod akv2k8s/azure-key-vault-controller-5fcc88dc45-zrqbn in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors\n"     
time="2020-09-23T16:19:44Z" level=error msg="error syncing 'abcd-namespace/zsecret-sync': Failed to get secret for 'zsecret-sync' from Azure Key Vault 'abcd-kv-01', requeuing"

No Error in MIC:

Only Error in NMI:
I0923 16:35:44.203145       1 server.go:192] status (200) took 6048996 ns for req.method=GET reg.path=/metadata/instance req.remote=10.5.0.32
E0923 16:35:48.545403       1 server.go:371] failed to get matching identities for pod: akv2k8s/azure-key-vault-controller-5fcc88dc45-zrqbn, error: getting assigned identities for pod akv2k8s/azure-key-vault-controller-5fcc88dc45-zrqbn in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I0923 16:35:48.545445       1 server.go:192] status (404) took 80002718258 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.5.0.17

**Comment by torresdal** [comment]
@zaidmohd I haven't had time to publish the release docs yet, but there it would say that `customAuth.podIdentitySelector` not longer exists. You should just pass it in as a label instead, using `webhook.podLabels`. See https://github.com/SparebankenVest/public-helm-charts/tree/master/stable/azure-key-vault-env-injector#configuration for details.

**Comment by torresdal** [comment]
See #55 - this is solved now and I believe this is related. Please reopen if not.

**Comment by ittennull** [comment]
>The only way (for security reasons) to output the secret, is for your application to output it in the logs.

That's not true. I often check injected secrets by opening a shell in a pod and running `cat /proc/1/environ | xargs -0 -L1 |sort` (parameters to `xargs` may differ depending on base image), the number "1" is the PID of your process, usually it's the first process, sometimes it's not, then it's the second or third number from `ls /proc/`. Injector doesn't magically hide secrets, it only makes it a bit more difficult to read them

**Comment by torresdal** [comment]
@ittennull Good point. But I believe if you wanted to prevent that, it could be done using `securityContext`, but I would need to test that unless someone can confirm?
