### ISSUE TITLE
Injector error: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by kuburoman** [SparebankenVest/azure-key-vault-to-kubernetes#13]
Hi, i deployed injector 0.1.14 and in logs i see following error.

Run on AKS version 1.13.5
On AKS 1.12.4 everything works fine.

```
2019/08/09 12:06:21 [WARN] no metrics recorder active
2019/08/09 12:06:21 [WARN] no tracer active
2019/08/09 12:06:21 [INFO] listening on :443
2019/08/09 12:06:29 http: TLS handshake error from 10.164.202.20:43382: tls: first record does not look like a TLS handshake
```

**Comment by torresdal** [comment]
Hi,

I suspect this is because of missing root CA certs on your image as described here: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes#env-injector---x509-certificate-signed-by-unknown-authority

Could you please check and let us know?

**Comment by torresdal** [comment]
Haven't seen this after this was reported. Closing for now. Please reopen if needed.
