### ISSUE TITLE
Error with Inject - Forbidden

### ISSUE THREAD

**Issue by zaidmohd** [SparebankenVest/azure-key-vault-to-kubernetes#130]
Inject not working for application code, but works for the test pod.

Working with the below environment.
AKV2K*s 1.1
Controller 1.1.0
Injector 1.1.7
AKS 1.18.6
Default authentication (No Custom authentication)

time="2020-10-05T09:31:15Z" level=error msg="error getting azurekeyvaultsecret resource 'secret-inject', error: Get https://10.0.0.1:443/apis/spv.no/v1/namespaces/akv-test/azurekeyvaultsecrets/secret-inject: Forbidden" application=env-injector component=akv2k8s namespace=akv-test

**Comment by torresdal** [comment]
@zaidmohd any chance you could share your Deployment/Pod spec? This indicates that the Pod for your application does not have access to read AzureKeyVaultSecret. Are you trying to access a AzureKeyVaultSecret outside the Pod namespace? Or does your application Pod run under a ServiceAccount without RBAC access to AzureKeyVaultSecrets?

**Comment by zaidmohd** [comment]
@torresdal not doing anything as such. Simple deployment file with custom image. And secrets are used as environment variable. 
I am able to access the same secret using the test pod. This app pod created in the same ns as test pod. My pod doesn't run under a service account. I can see init container attached and terminated.

No RBAC or AAD enabled at cluster

why is it going to 10.0.0.1?

**Comment by torresdal** [comment]
@zaidmohd there must be something that prevents your application pod to access AzureKeyVaultSecret resources, or any other Kubernetes resources. Without actually seeing your configuration it's hard to help. 

Istio installed preventing in-cluster communication?
You say no RBAC - I interpret that as no custom RBAC rules, but RBAC is actually enabled in cluster? (cause akv2k8s does not work without RBAC - states so in requirements)

10.0.0.1 should be the internal address of the Kubernetes API in your cluster.

**Comment by torresdal** [comment]
Closing for now @zaidmohd - reopen if this is still an issue

**Comment by zaidmohd** [comment]
@torresdal We were using proxy in the microservice, after adding the K8s service CIDR in No Proxy it worked.
