### ISSUE TITLE
[BUG] 404 getting credentials

### ISSUE THREAD

**Issue by dansantee** [SparebankenVest/azure-key-vault-to-kubernetes#137]
I have a pod running on AKS using AGIC for the ingress and I'm having an issue getting secret injection to work. Everything installs and looks good but once my pod spins up I get an error and it shuts down. Logs show a 404 while attempting to get credentials.

I'm wondering if this is due to "podName" getting the url of the ingress (https://zzz.com) instead of the container name. The pod has a normal-looking pod name (e.g. xxxxx-xxxxxx-xxxxx).

Is there some kind of label or setting that I've missed to get the podName to use the correct name during the call to the injector?

> time="2020-10-09T21:28:10Z" level=info msg="using sentralized akv2k8s auth service for authentiction with azure key vault" application=env-injector component=akv2k8s namespace=fleet
> time="2020-10-09T21:28:10Z" level=info msg="found original container command to be /usr/local/bin/docker-entrypoint.sh [docker-entrypoint.sh /bin/sh -c npm run start:dist]" application=env-injector component=akv2k8s namespace=fleet
> time="2020-10-09T21:28:10Z" level=info msg="requesting azure key vault oauth token from https://azure-key-vault-env-injector.akv2k8s.svc:443/auth/fleet/https://fleet.zzzzzzz.com" application=env-injector component=akv2k8s namespace=fleet
> time="2020-10-09T21:28:10Z" level=fatal msg="failed to get credentials, error: failed to get credentials, 404 Not Found"

**Comment by torresdal** [comment]
@dansantee yea, you're right. It passes on HOSTNAME as podname, which is usually the podname, but not always. I'll see if I can patch in a fix for this tomorrow. Thanks for letting us know.

**Comment by torresdal** [comment]
@dansantee Latest chart (`azure-key-vault-env-injector: 1.1.18` or `akv2k8s: 1.1.23`) now contains new versions of the images `spvest/azure-keyvault-webhook:1.1.10` and `spvest/azure-keyvault-env:1.1.1`. Please let us know if this fixes your problem, thanks.

**Comment by dansantee** [comment]
I can confirm that after updating the injector and restarting the pod that this works as expected - the pod name is used in the auth token get and secrets are injected successfully. Thanks very much!
