### ISSUE TITLE
[BUG] ccontroller crashing when trying to pull a Certificate created by importing a backup

### ISSUE THREAD

**Issue by daseth** [SparebankenVest/azure-key-vault-to-kubernetes#140]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Describe the bug**
The controller is crashing when i create a resource that syncs a Azure KeyVault certificate to a K8s TLS secret. The certificate is one that i have created by backing up from another KeyVault and restoring to my KeyVault.

**To Reproduce**
1.  Back up a certificate from a different vault. Restore to the target vault from which you'll be syncing.

2. Create a AZKV2K8s resource:
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: a-name
spec:
  vault:
    name: myVault # name of key vault
    object:
      name: name-of-imported-cert
      type: certificate
  output: 
    secret:
      name: name-of-cert-in-the-k8s-cluster # kubernetes secret name
      type: kubernetes.io/tls # kubernetes secret type
3. Contorller crashes and is unable to start (see logs)

4. As soon as i delete the problematic resource pointing to the imported certificate, the controller starts and is able to sync other certificates and secrets

**Expected behavior**
A TLS secret should be created from that KeyVault certificate

**Logs**
If applicable, add logs to help explain your problem.
[azure-keyvault-controller.log](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/files/5400081/azure-keyvault-controller.log)

**Additional context**

**Comment by torresdal** [comment]
@daseth Thanks for reporting this. Hard to say from the logs what happened here, other than it fails trying to download the certificate using the Azure Key Vault client. Not seen this issue before. We'll look into it and see if we can manage to replicate the issue, but first please let us know:

* which version of akv2k8s are you running (image tag of the controller)?
* what type of certificate is it? (pfx, pem?)
* does the certificate have a private key and is the private key backed up and restored together with the certificate?
* are you able to download the certificate using `Download in PFX/PEM format` in the Azure Portal and/or using the `az keyvault download` command?

**Comment by daseth** [comment]
Controller: spvest/azure-keyvault-controller:1.1.0
Certificate is PFX (pkcs 12)
Certificate had a private key included initially. Not sure if it gets exported when doing a "Download backup" from the azure portal
Yes i am able to download it in PFX format. I am actually consuming the certificate from the source Keyvault inside AKV2K8s to sync it as a TLS secret and use it in an ingress.

**Comment by torresdal** [comment]
As mentioned we have no other reports of this issue and we haven't been able to find out anything more. Closing for now, but if this is still an issue (especially in upcoming 1.2 version), please re-open.
