### ISSUE TITLE
[BUG] config map deleted by Kubernetes garbage collector

### ISSUE THREAD

**Issue by gerstmeier** [SparebankenVest/azure-key-vault-to-kubernetes#153]
**Note: Make sure to check out known issues (https://akv2k8s.io/troubleshooting/known-issues/) before submitting**

**Components and versions**
Select which component(s) the bug relates to with [X].

[x] Controller, version: `x.x.x` (docker image tag)
[x ] Env-Injector (webhook), version: `x.x.x` (docker image tag)
[ ] Other

**Describe the bug**
The akv2k8s-ca configmap has an owner in the namespace where the injector/controllers are deployed and not in the monitored namespace. Recent Kubernetes versions do not allow owners in different namespaces and therefore the garbage collector deletes the config map every once in a while.

**To Reproduce**
I'm running Kubernetes 1.19.3. Deploy the akv2k8s component to namespace a. Create a second namespace b and deploy some pods with akv2k8s annotations (The owner of the created config map in namespace b should then point to a secret in namespace a). Wait until the Kubernetes garbage collector has done its work. The config map should now be deleted. Try to run a second annotated pod...

**Expected behavior**
The config map should not have a owner in a different namespace and should not be deleted by the garbage collector.

**Logs**
If applicable, add logs to help explain your problem.

```
paste log here...
```

**Additional context**

**Comment by torresdal** [comment]
Hey @gerstmeier - you are correct about it having owner in different namespace. I'll take a quick look to see if there is a simple patch, if not the upcoming 1.2 version will not use these config maps at all as a much better solution was used. I'll keep you posted.

**Comment by torresdal** [comment]
This will not be fixed in 1.1. Version 1.2 is about to come out and we spent a lot of time getting rid of to many issues introduced in 1.1.

So - solved in 1.2.
