### ISSUE TITLE
[BUG] env-injector pods go into CrashLoopBackOff - "failed to read azure config"

### ISSUE THREAD

**Issue by MattMencel** [SparebankenVest/azure-key-vault-to-kubernetes#156]
**Components and versions**
Select which component(s) the bug relates to with [X].

[X] Env-Injector (webhook), version="1.2.1" commit="5ad4093" buildDate="2021-02-28T21:27:59Z"

**Describe the bug**

env-injector pods go into CLBO with this...

The controller starts fine.

**To Reproduce**

Install with Helm chart version 2.0.2, and these custom values. All others are default.

```
    addAzurePodIdentityException: true
    cloudConfig: /etc/kubernetes/azure.json
    env_injector:
      securityContext:
        allowPrivilegeEscalation: true # must be true if using aks identity
        runAsUser: 65534
```

**Expected behavior**
Expected env-injector pods to start.

**Logs**

```
kubectl logs -f akv2k8s-envinjector-66f44844cc-8frjr
I0304 21:07:58.819265       1 version.go:31] "version info" version="1.2.1" commit="5ad4093" buildDate="2021-02-28T21:27:59Z" component="webhook"
I0304 21:07:58.819413       1 main.go:289] "active settings" httpPort="8080" httpPortExternal="80" tlsPort="8443" tlsPortExternal="443" mtlsPort="9443" mtlsPortExternal="9443" serveMetrics=false authType="azureCloudConfig" useAuthService=true dockerInspectionTimeout=20 cloudConfigPath="/etc/kubernetes/azure.json" logLevel="2" authServiceName="akv2k8s-envinjector" mtlsPortExternal="9443" mtlsPort="9443"
E0304 21:07:58.820552       1 main.go:302] "failed to get credentials for azure key vault" err="failed to read azure config"
```

**Additional context**

- Kubernetes cluster version: 1.18.14
- aad-pod-identity is enabled in the cluster. 
- The cluster is using a Service Principal, not a Managed Identity.

**Comment by torresdal** [comment]
Unfortunately version 1.2.1 of env injector had a issue which is patched in 1.2.2. Please use Helm chart >= 2.0.5 which has the 1.2.2 version of env injector. 

Let us know if that fixes your problem. Thanks.

**Comment by MattMencel** [comment]
Still seeing an issue...

```
kubectl logs -f akv2k8s-envinjector-7c75df8668-tnqgr --previous
I0304 21:44:36.715096       1 version.go:31] "version info" version="1.2.2" commit="87cd17d" buildDate="2021-02-28T22:09:06Z" component="webhook"
I0304 21:44:36.715243       1 main.go:289] "active settings" httpPort="8080" httpPortExternal="80" tlsPort="8443" tlsPortExternal="443" mtlsPort="9443" mtlsPortExternal="9443" serveMetrics=false authType="azureCloudConfig" useAuthService=true dockerInspectionTimeout=20 cloudConfigPath="/etc/kubernetes/azure.json" logLevel="2" authServiceName="akv2k8s-envinjector" mtlsPortExternal="9443" mtlsPort="9443"
E0304 21:44:36.716861       1 main.go:300] "failed to get credentials for azure key vault" err="failed to read azure config"
```

**Comment by MattMencel** [comment]
Hmm... commenting these from my values.yaml allowed the env-injector to run.

```
env_injector:
  # securityContext:
  # allowPrivilegeEscalation: true # must be true if using aks identity
  # runAsUser: 65534
```

Likely the `runAsUser` was the problem since `allowPrivilegeEscalation` is true by default?

Those values worked in a previous release. I'm not sure which since I was pinning to `latest` for a while, but one of the recent beta ones.

**Comment by 181192** [comment]
> Hmm... commenting these from my values.yaml allowed the env-injector to run.
> 
> ```
> env_injector:
>   # securityContext:
>   # allowPrivilegeEscalation: true # must be true if using aks identity
>   # runAsUser: 65534
> ```
> 
> Likely the `runAsUser` was the problem since `allowPrivilegeEscalation` is true by default?
> 
> Those values worked in a previous release. I'm not sure which since I was pinning to `latest` for a while, but one of the recent beta ones.

@MattMencel `allowPrivilegeEscalation` is needed when deploying in AKS using the AKS identity (reads the `/etc/kubernetes/azure.json` file from host path). And it won't work with setting `runAsUser`to other than 0 (root) because the file is mounted as root by default. If not running in AKS (or not using cloud config) `allowPrivilegeEscalation` can be set to `false` allowing to set `runAsUser`.

**Comment by 181192** [comment]
Closing this issue now @MattMencel, feel free to reopen if its still an issue :blush:
