### ISSUE TITLE
Consistent timeout issue pulling images

### ISSUE THREAD

**Issue by dwumpus** [SparebankenVest/azure-key-vault-to-kubernetes#16]
I have three clusters a dev, uat, and prod cluster (don't get me started), The Dev and UAT clusters seem to work perfectly with the environment variable injector.  Love the way it works BTW!  Though the clusters are identical, save the vnet they are configured on, I am getting a timeout when trying to pull images from the prod environment.  The timeout only occurs on namespaces that have the injector enabled.   I am not necessarily looking for anyone to solve this issue directly, but more to offer some troubleshooting suggestions.  Here is a bit more information...  Helm appears healthy and upgraded, as I use it for plenty of other things in the environment.  Kubernetes is running at 1.13.10 in all three environments.  

running kubectl logs on the injector pod (in the default namespace) reveals this:
time="2019-08-27T18:14:42Z" level=info msg="pulling docker image tmocontainers.azurecr.io/eob/web-app:20190827.1 to get entrypoint and cmd, timeout is 30 seconds"
2019/08/27 18:15:12 [ERROR] admission webhook error: failed to get auto cmd, error: failed to pull docker image 'tmocontainers.azurecr.io/eob/web-app:20190827.1', error: context deadline exceeded

I have ensured that authorization policies are in place between the SP in aks and the ACR, I also added a docker login secret - the logs indicates that they find those fine... but apparently just cannot start my pods.  

Running the deployment in another namespace without the injection enabled starts the pod just fine... I have created another cluster on the same subnet and it also fails when enabling the injection in the namespace.  

Finally, I'll continue looking for an answer and may offer a pull-request if I find there is something that can be done to correct it from a code perspective, but honestly it seems mroe environmental, and would love to have some better information in the logs, or know about where else I could look to get that information.  Thanks!

**Comment by gldraphael** [comment]
Same here, I'm seeing:

```
time="2019-09-11T17:56:04Z" level=info msg="found pod to mutate in namespace 'namespacename'"
time="2019-09-11T17:56:04Z" level=info msg="found container 'service-dev' to mutate"
time="2019-09-11T17:56:04Z" level=info msg="checking for env vars containing '@azurekeyvault' in container servicename-dev"
time="2019-09-11T17:56:04Z" level=info msg="found env var: servicebus-secret@azurekeyvault"
time="2019-09-11T17:56:04Z" level=info msg="found env var: serilog-secret@azurekeyvault"
time="2019-09-11T17:56:04Z" level=info msg="found env var: storage-secret@azurekeyvault"
time="2019-09-11T17:56:04Z" level=info msg="found env var: servicename-redis-secret@azurekeyvault"
time="2019-09-11T17:56:04Z" level=info msg="found env var: aws-accesskey-secret@azurekeyvault"
time="2019-09-11T17:56:04Z" level=info msg="found env var: aws-secret@azurekeyvault"
time="2019-09-11T17:56:04Z" level=info msg="did not find credentials to use with registry 'org.azurecr.io' - getting default credentials"
time="2019-09-11T17:56:04Z" level=info msg="using default credentials for docker registry with clientid: xxxxxxxx-xxxx-0000-xxxx-xxxxxxxxxxxx"
time="2019-09-11T17:56:04Z" level=info msg="pulling docker image org.azurecr.io/containername:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx to get entrypoint and cmd, timeout is 30 seconds"
time="2019-09-11T17:56:34Z" level=info msg="docker image org.azurecr.io/containername:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx pulled successfully"
time="2019-09-11T17:56:34Z" level=info msg="inspecting container image org.azurecr.io/containername:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, looking for entrypoint and cmd"
2019/09/11 17:56:34 [ERROR] admission webhook error: failed to get auto cmd, error: failed to inspect docker image 'org.azurecr.io/containername:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', error: context deadline exceeded
```

In my case the docker image is being pulled from ACR using the SP credentials available at `/etc/kubernetes/azure.json`. The SP has `GET` access on the key-vault being referenced.

**Comment by torresdal** [comment]
I believe we've found the issue and a new release is available: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/releases/tag/0.1.15

The problem was a timeout issue when downloading Docker images. Timeout is now set to 2 minutes by default, but can be configured. Updated to the documentation is coming shortly.

**Comment by gldraphael** [comment]
The new chart worked. Thanks!

```
time="2019-09-12T07:35:17Z" level=info msg="containers mutated and pod updated with init-container and volumes"
```
