### ISSUE TITLE
[Question] What is the default resync interval and is it configurable?

### ISSUE THREAD

**Issue by dineshsharmads** [SparebankenVest/azure-key-vault-to-kubernetes#160]
How often does controller check Azure Key vault for new versions?
Is Resync Period configurable?

**Comment by 181192** [comment]
Hello @dineshsharmads, default re-sync period is every ~30 seconds and it is not configurable :blush:

**Comment by dineshsharmads** [comment]
Thanks @181192. 
We have multiple instances of a single tenant app which requires multiple TLS secrets. But refreshing secrets every 30 seconds is sending too many requests to Keyvault and it seems to impact the cost. It will be good to have resync period configurable on the controller or on the CRD (even better) in the future.

**Comment by 181192** [comment]
@dineshsharmads Agreed, now akv2k8s is just using the Informer to reconcile, having a possibility to define sync interval via CRD could definitely be a nice feature.
Turning the sync interval down for the reconcile loop on the other hand would make the controller "slower" on picking up changes in the CRD and apply to the cluster, and that may not be the case you want, but it will make less requests to Key Vault.
Feel free to contribute with a PR, or specify the API for the CRD.
Looking at other projects like Flux v2, they implemented something similar with a reconcile interval config for most of the CRD's.

**Comment by sdwerwed** [comment]
@181192 Hello, in our infra it is using 1.5million requests to key-vault in per 24h. More specifically 11.9 requests per minute per secret, is that expected?
