### ISSUE TITLE
[Question] ensureserverfirst does not check if the certificates are already in order

### ISSUE THREAD

**Issue by dineshsharmads** [SparebankenVest/azure-key-vault-to-kubernetes#161]
I'm not sure if this is a bug or intended by design.
But ensureserverfirst does not check if the certificates are already in order and always re-orgs the certificate.
This leads to the server certificate between CA certificates.

**To Reproduce**
Import a PFX into Keyvault.
Sync secret to AKS using chainorder: ensureserverfirst
The secret is not readable by Ingress.

**Comment by 181192** [comment]
Hello @dineshsharmads, yes current implementation does not check if the certificate are already in order. Just assumes if the `ensureserverfirst` property is set..

https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/bb751aef3405ab1b0118576f73635667e8481a10/pkg/azure/keyvault/client/certificate.go#L187-L192
