### ISSUE TITLE
AzureKeyVault API invalid URL error

### ISSUE THREAD

**Issue by fmorales1multicaja** [SparebankenVest/azure-key-vault-to-kubernetes#17]
Hi,

version: spvest/azure-keyvault-controller:0.1.14

When trying to get secret from AKV, the AKV API responses with invalid URI error:

`failed to get secret value for 'AZURE_SECRET' from Azure Key vault using object name '[NAME]', error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://XX.vault.azure.net/secrets/YY/450e17bd04ac4e58bbb49bd1a67f1?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request - Invalid URL</h2>\r\n<hr><p>HTTP Error 400. The request URL is invalid.</p>\r\n</BODY></HTML>\r\n`

If I copy the url logged in the controller and try to get the secret directly from AKV, removing the suffix "?api-version=2016-10-01", it gives me no error, but if I append that suffix it gives me the same invalid URI error.

Does someone else has the same error?

**Comment by torresdal** [comment]
Probably same as this: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes#env-injector---x509-certificate-signed-by-unknown-authority

**Comment by torresdal** [comment]
Closing - expect solved as per answer above
