### ISSUE TITLE
Internal error occurred: failed calling webhook "pods.env-injector.admission.spv.no

### ISSUE THREAD

**Issue by leonids2005** [SparebankenVest/azure-key-vault-to-kubernetes#170]
**Note: Make sure to check out known issues (https://akv2k8s.io/troubleshooting/known-issues/) before submitting**

**Components and versions**
Select which component(s) the bug relates to with [X].

[ ] Controller, version: `` (docker image tag)
[X] Env-Injector (webhook), version: `1.1.26` (docker image tag)
[ ] Other

**Describe the bug**

recently we started getting the following errors in our replica sets for pods which needs to be mutated.

Internal error occurred: failed calling webhook "pods.env-injector.admission.spv.no": Post https://akv2k8s-envinjector.akv2k8s.svc:443/pods?timeout=30s: dial tcp 10.0.127.151:443: connect: connection refused

Have you seen this before and what is the best way to troubleshoot it.

We have tried to delete all your replica sets but it did not help.  We have not reinstalled your bundle yet. Would like to investigate it.

One more thing which is may not be very relevant.  
REcently, we have tried to upgrade your tool to recent version but because of breaking changes we could not do it...
But in the injector service  we see the reference to version 2 chart

  labels:
    app.kubernetes.io/component: akv2k8s-webhook
    app.kubernetes.io/instance: akv2k8s
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: akv2k8s
    helm.sh/chart: akv2k8s-2.0.10

It looks like we need to reinstall your tool

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

```
paste log here...
```

**Additional context**

**Comment by 181192** [comment]
Hello @leonids2005 :blush: 

Correct, due to breaking changes upgrade from Helm chart v1.1.x to v2 is not possible. And v1 chart must be uninstalled.
Can you check if there are multiple mutation webhook configurations available in your cluster, that could describe the behavior you are observing?
```
kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io 
```

**Comment by 181192** [comment]
Closing this issue now @leonids2005, but feel free to open if any further issues
