### ISSUE TITLE
Allow controller to use custom authentication per namespace

### ISSUE THREAD

**Issue by tamer-abdulghani** [SparebankenVest/azure-key-vault-to-kubernetes#171]
**Problem**
We have multiple namespaces which are related to different departments. Each department has it is own subscription on azure, meaning has its own key vault. This key vault must not be accessible by other departments. Also, each department has its own service pricinple which only has access to that subscription. 

Thus the controller cannot have one service princinple that access all key vaults on azure. So we cannot provide this kind of service principle to the controller. 

**Desired behaviour**

It could be nice to have a way to define a custom authentication for the controller that let him fetch key vault secrets per namespace using that namespace's service pricinple.

in other word, each namespace will have service principle (client-id/client-secret), and we want to tell the controller somehow to use those credentials when fetching key vault secrets for this particular namespace. while for another namespace, the controller has to use different service principle.

**Comment by 181192** [comment]
Hi @tamer-abdulghani,

This change #178 makes it possible to run multiple controllers in the same namespace using different credentials for the controller and targeting different AzureKeyVaultSecret's

**Comment by kristeey** [comment]
Closing this issue as controller version >= v1.3 allows running multiple controllers in cluster/namespace. See https://akv2k8s.io/installation/requirements/#installation-of-multiple-controllers
