### ISSUE TITLE
[Question] migration from legacy charts to akv2k8s chart

### ISSUE THREAD

**Issue by agarwalarjun123** [SparebankenVest/azure-key-vault-to-kubernetes#176]
Can you please guide us about the steps to migrate easily from legacy charts to akv2k8s charts.

**Comment by 181192** [comment]
Hi @agarwalarjun123 :relaxed: Did you look at the documentation for upgrading? https://akv2k8s.io/installation/upgrade/#upgrading-helm-chart-version-to-v2xx-from-v11x

**Comment by agarwalarjun123** [comment]
thanks. the issue has been resolved
