### ISSUE TITLE
[Question] Backward compatibility with CRD v1alpha1

### ISSUE THREAD

**Issue by agarwalarjun123** [SparebankenVest/azure-key-vault-to-kubernetes#177]
I have migrated from legacy chart version to akv2k8s with the same CRD version v1alpha1. this does not seem to inject secret to container on aks. Can you please let me know the reason behind it?

**Comment by 181192** [comment]
Hi @agarwalarjun123, I think we need some more information about your setup to be able to help (helm install command, logs, etc..).
If you have just migrated from legacy chart check that there is only one MutatingWebhookConfiguration for akv2k8s.

```
kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io
```
