### ISSUE TITLE
[FEATURE]  Add labels to resulting secrets/certificates from AzureKeyVaultSecret

### ISSUE THREAD

**Issue by daseth** [SparebankenVest/azure-key-vault-to-kubernetes#179]
Please consider adding an option to label the resulting Kubernetes secrets by labeling the AzureKeyVaultSecret resource and passing on that label to the Kubernetes secret that gets created.

**Comment by 181192** [comment]
Hi @daseth! 

This is a great idea, any input on how the API should be designed or a PR would be appreciated :pray:

**Comment by 181192** [comment]
This is already implemented in 2bc3dc2c6ca6ea21b250c6e3674c8959a296a16e released in v1.1.0, forward any labels and annotations from AzureKeyVaultSecret to Kubernetes Secret #104.

Closing issue
