### ISSUE TITLE
[FEATURE] ConfigMap template support

### ISSUE THREAD

**Issue by lukasmrtvy** [SparebankenVest/azure-key-vault-to-kubernetes#18]
It would be super usefull, if something like this:
https://github.com/Soluto/kamus/tree/master/init-container#custom-templating-support
will be supported.
Not all images/applications handles configuration from environment variables and sometimes its needed to store secret in configMap.
Thanks

**Comment by torresdal** [comment]
Agree @lukasmrtvy. Basically two things then: 

1. Support for ConfigMap
2. Support for templating

The first should be doable in reasonable time. The second will require some more thought. Mind if I split these in two?

**Comment by torresdal** [comment]
Support for ConfigMap is now available in 1.2-beta - soon to be released.

**Comment by torresdal** [comment]
We will not add template support at this time, unless someone provide a PR. ConfigMaps will be supported from v1.2.
