### ISSUE TITLE
[FEATURE] - Is it possible to use with 1 KeyVault per namespace?

### ISSUE THREAD

**Issue by patpicos** [SparebankenVest/azure-key-vault-to-kubernetes#19]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Is it possible to run the env injector where multiple keyvaults are used. We are looking to use 1 keyvault per application which would be namespaced.

I guess my question ties to the authentication piece of the solution

**Describe alternatives you've considered**
N/A

**Additional context**

N/A

**Comment by torresdal** [comment]
Hi @patpicos. To answer your question literally, the answer is yes. You define one AzureKeyVaultSecret definition per Azure Key Vault Secret, and each of your definitions can point to different Key Vaults.

As for auth, the default auth is using the built in AKS identity, meaning this will need access to all your Key Vaults in question. 

If your question is about limiting access to Azure Key Vaults per individual namespaces, the answer is no. That is however something we're looking into, so an example of your use case would be nice.

Thanks.

**Comment by scivm** [comment]
We are using one key vault per application and also 1 key vault per aks cluster.
