### ISSUE TITLE
Deployment never schedules webhook container

### ISSUE THREAD

**Issue by mvarga6** [SparebankenVest/azure-key-vault-to-kubernetes#2]
Been playing around with this chart but seem to be missing something critical as a deployment created from a fresh helm install never yields available pods. (note the Replicas line)

```
$ kubectl describe deployments keyvault-azure-key-vault-env-injector
Name:                   keyvault-azure-key-vault-env-injector
Namespace:              default
Labels:                 app=azure-key-vault-env-injector
                        chart=azure-key-vault-env-injector-0.1.2
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=azure-key-vault-env-injector,release=keyvault
Replicas:               1 desired | 0 updated | 0 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=azure-key-vault-env-injector
                    release=keyvault
  Service Account:  keyvault-azure-key-vault-env-injector
  Containers:
   azure-key-vault-env-injector:
    Image:      spvest/azure-keyvault-webhook:0.1.10
    Port:       443/TCP
    Host Port:  0/TCP
    Environment:
      TLS_CERT_FILE:            /var/serving-cert/servingCert
      TLS_PRIVATE_KEY_FILE:     /var/serving-cert/servingKey
      AZUREKEYVAULT_ENV_IMAGE:  spvest/azure-keyvault-env:0.1.10
      AAD_POD_BINDING_LABEL:     (v1:metadata.labels['aadpodidbinding'])
      DEBUG:                    false
# mounts & volumes emitted
OldReplicaSets:    keyvault-azure-key-vault-env-injector-c49946b4b (0/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  7m35s  deployment-controller  Scaled up replica set keyvault-azure-key-vault-env-injector-c49946b4b to 1
```
As you can see there's 1 desired replica and it stays as 1 unavailable.  

Creating an `AzureKeyVaultSecret` resource named `my-test-secret` (following the [README](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes)), then scheduling a simple pod that would utilize the injections,

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kv-tester
  labels:
    app: kv-tester
spec:
  containers:
    - name: kv-tester
      image: debian
      command: ["printenv"]
      env:
      - name: MY_SECRET
        value: my-test-secret@azurekeyvault
```
yields

```
$ kubectl create -f kubernetes/testing/kv-tester.yaml 

Error from server (InternalError): error when creating "kubernetes/testing/kv-tester.yaml": Internal 
error occurred: failed calling admission webhook "pods.azure-key-vault-env-
injector.admission.spv.no": Post https://keyvault-azure-key-vault-env-
injector.default.svc:443/pods?timeout=30s: net/http: request canceled while waiting for 
connection (Client.Timeout exceeded while awaiting headers)
```
It's pretty clear that it's trying to communicate with a service that has a deployment with no pods backing it.

**Why isn't the deployment scheduling the pods?**  I'm assuming things will work as expected from there because I've confirmed the service principal has the correct access to key vault instance.  Any help would be much appreciated, thank you.

**Comment by torresdal** [comment]
According to the error message you get, it cannot contact the webhook. If you run the following kube command, you can check if the webhook is installed:

`kubectl get MutatingWebhookConfiguration`

The output should be something like:

```
NAME                               CREATED AT
aks-webhook-admission-controller   2019-03-19T15:47:29Z
```

If that is OK, make sure you have enabled the env-injector for the namespace you're using (in your case `default`) as noted here: https://github.com/SparebankenVest/public-helm-charts/tree/master/stable/azure-key-vault-env-injector#installing-the-chart

If still not resolved and to better be able to help you, please provide the following information:

* The Kubernetes cluster version
* The AKS version (if using AKS)
* The Helm chart version used and any configuration overrides (`values.yaml`)

**Comment by torresdal** [comment]
Closing due to lack of response.
