### ISSUE TITLE
Cannot install - pods keep CrashLoopBackOff

### ISSUE THREAD

**Issue by jackchuong** [SparebankenVest/azure-key-vault-to-kubernetes#214]
Hi all,
I follow this instruction : https://akv2k8s.io/installation/on-azure-aks/
kubectl create ns akv2k8s
helm repo add spv-charts https://charts.spvapi.no
helm repo update
helm upgrade --install akv2k8s spv-charts/akv2k8s --namespace akv2k8s
Release "akv2k8s" does not exist. Installing it now.
NAME: akv2k8s
LAST DEPLOYED: Fri Jul 16 10:10:25 2021
NAMESPACE: akv2k8s
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Congratulations! You've successfully installed Azure Key Vault to Kubernetes.
For more information see the documentation at https://akv2k8s.io.

kubectl get all --namespace akv2k8s
NAME                                       READY   STATUS    RESTARTS   AGE
pod/akv2k8s-controller-d7c8c5f78-cwngb     1/1     Running   0          12s
pod/akv2k8s-envinjector-6685c8cc74-fts8q   0/1     Running   0          12s
pod/akv2k8s-envinjector-6685c8cc74-wpsj4   0/1     Running   0          12s

NAME                          TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                   AGE
service/akv2k8s-controller    ClusterIP   10.0.121.25   <none>        9000/TCP                  12s
service/akv2k8s-envinjector   ClusterIP   10.0.50.241   <none>        443/TCP,80/TCP,9443/TCP   12s

NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/akv2k8s-controller    1/1     1            1           12s
deployment.apps/akv2k8s-envinjector   0/2     2            0           12s

NAME                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/akv2k8s-controller-d7c8c5f78     1         1         1       13s
replicaset.apps/akv2k8s-envinjector-6685c8cc74   2         2         0       13s

kubectl get all --namespace akv2k8s
NAME                                       READY   STATUS             RESTARTS   AGE
pod/akv2k8s-controller-d7c8c5f78-cwngb     0/1     Error              2          6m8s
pod/akv2k8s-envinjector-6685c8cc74-fts8q   0/1     CrashLoopBackOff   2          6m8s
pod/akv2k8s-envinjector-6685c8cc74-wpsj4   0/1     CrashLoopBackOff   2          6m8s

NAME                          TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                   AGE
service/akv2k8s-controller    ClusterIP   10.0.121.25   <none>        9000/TCP                  6m8s
service/akv2k8s-envinjector   ClusterIP   10.0.50.241   <none>        443/TCP,80/TCP,9443/TCP   6m8s

NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/akv2k8s-controller    0/1     1            0           6m9s
deployment.apps/akv2k8s-envinjector   0/2     2            0           6m9s

NAME                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/akv2k8s-controller-d7c8c5f78     1         1         0       6m9s
replicaset.apps/akv2k8s-envinjector-6685c8cc74   2         2         0       6m9s

```
kubectl describe pod/akv2k8s-envinjector-6685c8cc74-fts8q --namespace akv2k8s
Name:         akv2k8s-envinjector-6685c8cc74-fts8q
Namespace:    akv2k8s
Priority:     0
Node:         aks-agentpool-19144222-vmss000003/10.240.0.4
Start Time:   Fri, 16 Jul 2021 10:10:06 +0700
Labels:       app.kubernetes.io/component=akv2k8s-webhook
              app.kubernetes.io/instance=akv2k8s
              app.kubernetes.io/name=akv2k8s
              pod-template-hash=6685c8cc74
Annotations:  checksum/config: 47992a9c3f0b36268b6292a1a0835c33314fe0ab80e7acd981870a9138ddefc9
Status:       Running
IP:           10.240.0.100
IPs:
  IP:           10.240.0.100
Controlled By:  ReplicaSet/akv2k8s-envinjector-6685c8cc74
Containers:
  webhook:
    Container ID:  containerd://928aae5564cf3feac9a9a19693c6d195a2ffe13c65d9c33bee42c1716382074b
    Image:         spvest/azure-keyvault-webhook:1.2.3
    Image ID:      docker.io/spvest/azure-keyvault-webhook@sha256:0c280111f9cbf5e14abb0000de1c1697652eb4953deccde51d579f8897a4ddb8
    Ports:         8443/TCP, 8080/TCP, 9443/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      --cloudconfig=/etc/kubernetes/azure.json
      --version=1.2.3
      --versionenvimage=1.2.2
      --v=2
      --logging-format=text
    State:          Running
      Started:      Fri, 16 Jul 2021 10:12:01 +0700
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 16 Jul 2021 10:10:07 +0700
      Finished:     Fri, 16 Jul 2021 10:12:00 +0700
    Ready:          False
    Restart Count:  1
    Readiness:      http-get https://:8443/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      HTTP_PORT:                        8080
      HTTP_PORT_EXTERNAL:               80
      TLS_PORT:                         8443
      TLS_PORT_EXTERNAL:                443
      MTLS_PORT:                        9443
      MTLS_PORT_EXTERNAL:               9443
      MTLS_PORT:                        9443
      RUNNING_INSIDE_AZURE_AKS:
      TLS_CERT_DIR:                     /var/serving-cert
      CA_CERT_DIR:                      /var/ca-cert
      ENV_INJECTOR_EXEC_DIR:            /azure-keyvault/
      WEBHOOK_AUTH_SERVICE:             akv2k8s-envinjector
      AUTH_TYPE:                        azureCloudConfig
      USE_AUTH_SERVICE:                 true
      AZUREKEYVAULT_ENV_IMAGE:          spvest/azure-keyvault-env:1.2.2
      DOCKER_IMAGE_INSPECTION_TIMEOUT:  20
      METRICS_ENABLED:                  false
    Mounts:
      /etc/kubernetes/azure.json from azureconf (ro)
      /var/ca-cert from ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from akv2k8s-envinjector-token-77wlq (ro)
      /var/serving-cert from serving-cert (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  serving-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  akv2k8s-envinjector-tls
    Optional:    false
  ca-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  akv2k8s-envinjector-ca
    Optional:    false
  azureconf:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  akv2k8s-envinjector-token-77wlq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  akv2k8s-envinjector-token-77wlq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  3m9s                 default-scheduler  Successfully assigned akv2k8s/akv2k8s-envinjector-6685c8cc74-fts8q to aks-agentpool-19144222-vmss000003
  Normal   Pulled     74s (x2 over 3m8s)   kubelet            Container image "spvest/azure-keyvault-webhook:1.2.3" already present on machine
  Normal   Created    74s (x2 over 3m8s)   kubelet            Created container webhook
  Normal   Started    74s (x2 over 3m8s)   kubelet            Started container webhook
  Warning  Unhealthy  33s (x16 over 3m3s)  kubelet            Readiness probe failed: Get "https://10.240.0.100:8443/healthz": dial tcp 10.240.0.100:8443: connect: connection refused
```

kubectl logs pod/akv2k8s-envinjector-6685c8cc74-fts8q --namespace akv2k8s
I0716 03:12:01.564919       1 version.go:31] "version info" version="1.2.3" commit="a7b2d04" buildDate="2021-03-11T07:33:20Z" component="webhook"
I0716 03:12:01.564989       1 main.go:289] "active settings" httpPort="8080" httpPortExternal="80" tlsPort="8443" tlsPortExternal="443" mtlsPort="9443" mtlsPortExternal="9443" serveMetrics=false authType="azureCloudConfig" useAuthService=true dockerInspectionTimeout=20 cloudConfigPath="/etc/kubernetes/azure.json" logLevel="2" authServiceName="akv2k8s-envinjector" mtlsPortExternal="9443" mtlsPort="9443"
E0716 03:13:53.570450       1 main.go:306] "failed to get authorizer from azure key vault credentials" err="adal: Refresh request failed. Status Code = '404'. Response body: no azure identity found for request clientID 5522##### REDACTED #####1acc\n"

How can I install it ?

**Comment by jackchuong** [comment]
Problem solved by upgrade akv2k8s release with --set addAzurePodIdentityException=true.

**Comment by cacizi41** [comment]
Could someone explain why "--set addAzurePodIdentityException=true" solved the problem? I had unhealthy probe readiness issue and this argument solved it as well.
