### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bpoudel1210** [SparebankenVest/azure-key-vault-to-kubernetes#24]
how can we sync multiple secrets? 
The document does not contain enough information. `https://akv2k8s.io/tutorials/4-multi-value-secret`

**Comment by torresdal** [comment]
@bpoudel1210  You define multiple AzureKeyVaultSecret's in Kubernetes. Example: https://akv2k8s.io/tutorials/1-secret

The documentation is still being updated, but the example you're pointing to (multi value secret) will be documented soon, but that is for ONE secret containing multiple values, in json or yaml format. Not how to get multiple secrets.

**Comment by bpoudel1210** [comment]
@torresdal Thanks for the quick response and providing this awesome programme. I am looking forward to using the `multi value secret` feature, once it is documented.

**Comment by mvvveen** [comment]
> @torresdal Thanks for the quick response and providing this awesome programme. I am looking forward to using the `multi value secret` feature, once it is documented.

create a yaml file with your secrets like so

foo: bar
other: secret

create the secret in keyvault
az keyvault secret set --name <secret-name-in-keyvault> --vault-name <keyvault-name> --file <the-file-you-just-created>

next create a yaml file for your akvs object

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: <some-name-for-the-akvs-object>
spec:
  vault:
    name: <kevault-name.
    object:
      name: <secret-name-in-keyvault>
      type: multi-key-value-secret # akv object type
      contentType: application/x-yaml
  output:
    secret:
      name: <the-name-of-the-secret-in-k8s># kubernetes secret name
      dataKey: Data
 
apply this file to your cluster
kubectl apply -f filename.yaml
