### ISSUE TITLE
[FEATURE] Sync multi value azure key vault secret text type to k8s secret

### ISSUE THREAD

**Issue by jackchuong** [SparebankenVest/azure-key-vault-to-kubernetes#249]
I want to sync multi value azure key vault secret text type to k8s secret , for example:
Laravel framework has ".env" file , it is text file, with content:
```
dbhost=localhost
dbname=mydb
dbuser=myuser
dbpass=mypass
```
I can create azure key vault secret from text file but I cannot sync to k8s secret because the contentType only support application/x-json or application/x-yaml for now.

**Comment by kristeey** [comment]
Have you tried the multi value key sync covered i this tutorial https://akv2k8s.io/tutorials/sync/4-multi-key-value-secret/ ? Is this sufficient for your use case?

**Comment by jackchuong** [comment]
> 
> 
> Have you tried the multi key value secret sync covered i this tutorial https://akv2k8s.io/tutorials/sync/4-multi-key-value-secret/ ? Is this sufficient for your use case?

Hi kristeey, it isn't , because akv2k8s Sync Multi Key Value Secret feature only supports contentType application/x-json or application/x-yaml for now.

**Comment by torresdal** [comment]
We're currently reviewing all old and new feature requests, and it's decided that his feature will not be added to akv2k8s.
