### ISSUE TITLE
AKV2K8S is not syncing secrets from RBAC enabled Keyvault

### ISSUE THREAD

**Issue by hirensharma** [SparebankenVest/azure-key-vault-to-kubernetes#251]
I have installed the recent version of AKV2K8S using helm chart on my AKS.

The secrets are synced the first time and it works flawlessly.

However, if I go back and change the secrets in KeyVault, I still continue to see the old values being referenced in in kubernetes secret. The only difference I have from what is mentioned in the documentation is that I have an RBAC enabled KV and I am using system identity with the role of "Secret Reader".

Any help is appreciated.

**Comment by tspearconquest** [comment]
Voting to close due to lack of response
