### ISSUE TITLE
[BUG] hostPath type check failed: /etc/kubernetes/azure.json is not a file

### ISSUE THREAD

**Issue by KristapsT** [SparebankenVest/azure-key-vault-to-kubernetes#26]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Describe the bug**
I am trying to run Azure Key Vault Env Injector in a local minikube Kubernetes cluster, with `customAuth.enabled` set to `true` to use client credentials and client credentials are specified as `env` values in the values file.

Here is my full valuesfile I pass to helm chart:
```
# Default values 

installCrd: true # if installing both controller and env injector, only one can install CRD
replicaCount: 1
debug: false

image:
  repository: spvest/azure-keyvault-webhook
  tag: 0.1.15
  pullPolicy: IfNotPresent

envImage:
  repository: spvest/azure-keyvault-env
  tag: 0.1.15
  
service:
  name: azure-keyvault-secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 443

# Set to true to use custom auth - see https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/README.md#authentication 
customAuth:
  enabled: true

  # set to true to enable auto injection of credentials
  autoInject: 
    enabled: true

    # if credentials are env vars, spesify name of the 
    # secret the env injector should create for
    # storing the credentials
    
    secretName: azure-key-vault-secret
    
    # uncomment to use aad-pod-identity (MSI) and point to a selector
    # if used, secretName must not be set
    
    # podIdentitySelector: <selector name>

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  AZURE_TENANT_ID: <redacted>
  AZURE_CLIENT_ID: <redacted>
  AZURE_CLIENT_SECRET: <redacted>

```

My understanding is that this should allow to run Azure Key Vault Env Injector outside of AKS in any Kubernetes cluster, yet the pod tries to access hostPaht /etc/kubernetes/azure.json which doesn't exists since it's not AKS.

**To Reproduce**
helm install elm install spv-charts/azure-key-vault-env-injector -f ../values.yaml
where values.yaml is my specified values file.

kubectl describe pod -l app=azure-key-vault-env-injector
It shows in Events:
```
Events:
  Type     Reason       Age              From               Message
  ----     ------       ----             ----               -------
  Normal   Scheduled    4s               default-scheduler  Successfully assigned default/injector-azure-key-vault-env-injector-96454db4-ln6hh to minikube
  Warning  FailedMount  1s (x4 over 4s)  kubelet, minikube  MountVolume.SetUp failed for volume "azureconf" : hostPath type check failed: /etc/kubernetes/azure.json is not a file
```

**Expected behavior**
Pod should start with no issues

**Comment by torresdal** [comment]
@KristapsT thanks for reporting this and describing your use case. Unfortunately custom auth have some issues and we will look into this promptly to get it fixed. We would appreciate if you could test and verify our fix when available. Is that ok for you?

**Comment by DeanPH** [comment]
@torresdal Has this been resolved or still work in progress?

**Comment by torresdal** [comment]
@DeanPH I beleive this should be solved with this PR for the Helm chart: SparebankenVest/public-helm-charts#17 - Chart version 0.1.7 of azure-key-vault-env-injector.

**Comment by torresdal** [comment]
Closing for now. Please reopen if this is still an issue in Chart version > 0.1.7

**Comment by maximefifen** [comment]
@torresdal i try to deploy azure keyvault controller on rancher, i follow this step:

1- 
kubectl apply -f https://raw.githubusercontent.com/sparebankenvest/azure-key-vault-to-kubernetes/master/crds/AzureKeyVaultSecret.yaml --namespace=akv2k8s

2-
helm repo add spv-charts http://charts.spvapi.no

3-
helm update

4-
helm upgrade -i akv2k8s spv-charts/akv2k8s --namespace akv2k8s --set keyVault.customAuth.enabled=true --set env.AZURE_TENANT_ID=<tenant id> --set env.AZURE_CLIENT_ID=<client id> --set env.AZURE_CLIENT_SECRET=<secret>

5-
the deployment finish well

but i also have the issue with azure-config:

MountVolume.SetUp failed for volume "azure-config" : hostPath type check failed: /etc/kubernetes/azure.json is not a file
--

**Comment by torresdal** [comment]
@maximefifen could you please open a new issue? So much has changed in 8 months that it just gets confusing to relate to an old closed bug. Then we will help you get this solved shortly. Thanks.

**Comment by torresdal** [comment]
Btw, you need to prefix with controller or env-injector. The new helm chart contains both. For env you can use global. See the helm repo for docs.
