### ISSUE TITLE
Facing issues when switching from Kubernetes secrets to azure vaults secrets

### ISSUE THREAD

**Issue by Kryotasin** [SparebankenVest/azure-key-vault-to-kubernetes#265]
Our application is a Typescript application. The configurations we used worked with Ansible code.

After deploying the pod, these are the logs.

```
I1013 18:35:18.068218       1 version.go:31] "version info" version="" commit="a7b2d04" buildDate="2021-03-11T07:33:36Z" component="vaultenv"
I1013 18:35:18.068443       1 main.go:176] "azure key vault env injector initializing"
E1013 18:35:18.068624       1 main.go:236] "binary not found" err="exec: \"username\": executable file not found in $PATH"
I1013 18:35:18.069481       1 main.go:245] "found original container command" cmd="" args=[username password]
I1013 18:35:18.069615       1 authentication.go:98] "checking if current auth service credentials are stale" url="http://azure-key-vault-to-k8s-akv2k8s-envinjector.extensions.svc:80/auth/com-dev/api-8596c6c7dd-jq4pc?secret=akv2k8s-api"
I1013 18:35:18.168503       1 authentication.go:111] "auth service credentials ok" url="http://azure-key-vault-to-k8s-akv2k8s-envinjector.extensions.svc:80/auth/com-dev/api-8596c6c7dd-jq4pc?secret=akv2k8s-api"
I1013 18:35:18.168894       1 authentication.go:147] "requesting azure key vault oauth token" url="https://azure-key-vault-to-k8s-akv2k8s-envinjector.extensions.svc:9443/auth/com-dev/api-8596c6c7dd-jq4pc"
I1013 18:35:18.213717       1 authentication.go:167] "successfully received oauth token"
I1013 18:35:18.529982       1 main.go:342] "secret injected into env var" azurekeyvaultsecret="com-dev/username-secret" env="username"
I1013 18:35:18.641144       1 main.go:342] "secret injected into env var" azurekeyvaultsecret="com-dev/password-secret" env="password"
I1013 18:35:18.641183       1 main.go:348] "starting process with secrets in env vars" cmd="" args=[username password]
E1013 18:35:18.641209       1 main.go:351] "failed to execute process" err="no such file or directory" process=""
```

**Comment by aharper273** [comment]
I suggest trying to run this example image in the docs which prints out the env variables just for you to test if they are actually being injected properly, I am not convinceed this is an issue with the akv2k8s tool yet. You might also be able to just add a command to your current config to be able to print envs without exec, but I'm not sure how you have it set up.

https://akv2k8s.io/tutorials/env-injection/1-secret/

for example:

`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akvs-secret-app
  namespace: <your-namespace>
  labels:
    app: akvs-secret-app
spec:
  selector:
    matchLabels:
      app: akvs-secret-app
  template:
    metadata:
      labels:
        app: akvs-secret-app
    spec:
      containers:
      - name: akv2k8s-env-test
        image: spvest/akv2k8s-env-test:2.0.1
        args: ["<your env name>"]
        env:
        - name: <your env name>
          value: "<your secret name>@azurekeyvault" # ref to akvs
`

**Comment by victorgetz** [comment]
We have the same issue with https://gogatekeeper.github.io/helm-gogatekeeper

a simple 

```
     - name: PROXY_CLIENT_ID
       value: "keycloak-gatekeeper-client-id@azurekeyvault"
```

does not work.

ENV Secret Injections are working for the Helm Charts in the same cluster.

**Comment by victorgetz** [comment]
Found the solution it is very obvious. In the helm charts stand:

  automountServiceAccountToken: false

Then for sure it will not work ...

**Comment by tspearconquest** [comment]
I recommend closing this issue. The proper solution is now documented in #424
