### ISSUE TITLE
Question: why does env injector insist on pulling the docker image?

### ISSUE THREAD

**Issue by PeterGrace** [SparebankenVest/azure-key-vault-to-kubernetes#27]
Hello,

I've got an environment where i'm trying to deploy resources in Azure Kubernetes and I'm running into an issue where env-injector is failing because it is trying to pull the docker image, but it cannot find an imagePullSecret and it cannot find an azure.json to use for proper auth.  I've solved the issue with populating an imagePullSecret, but technically I wouldn't have to do that.  env-injector seems to require this, however.  

My question is, why is it required that the env-injector pull the image on behalf of the pod admission controller?  Is it because mutating the pod via the webhook somehow prevents the scheduler or admission controller from getting the pod itself?

**Comment by torresdal** [comment]
Question answered. Closing issue.
