### ISSUE TITLE
[FEATURE] AzureKeyVaultResourceURI Form Environment

### ISSUE THREAD

**Issue by mayong43111** [SparebankenVest/azure-key-vault-to-kubernetes#28]
Dear, People in some countries don't use Global Azure, for example AzureChinaCloud , AzureGermanCloud and so on.  Could you use different urls in different environments?

https://docs.microsoft.com/en-us/azure/key-vault/key-vault-secure-your-key-vault

Global:
<vault-name>.vault.azure.net:443

Azure China 21Vianet:
<vault-name>.vault.azure.cn:443

Azure US Government:
<vault-name>.vault.usgovcloudapi.net:443

Azure Germany:
<vault-name>.vault.microsoftazure.de:443

**Comment by torresdal** [comment]
Hey @mayong43111. Agree. We'll make sure this can be configured going forward. Need to get back to you on eta.

**Comment by mayong43111** [comment]
> Hey @mayong43111. Agree. We'll make sure this can be configured going forward. Need to get back to you on eta.

I'm so glad.  but sorry， what's the eta ? I'm not familiar with github

**Comment by torresdal** [comment]
Just that we will need to get back to when we can deliver (estimated time of arrival).

**Comment by mayong43111** [comment]
:)  Our project hopes to be online by the end of next month. This morning, I clone this source code and update AzureKeyVaultResourceURI and build new images and push my private Docker Registry.  The environment variable (  AZURE_ENVIRONMENT ) was manually modified  for Azure/go-autorest .  So far so good , Of course, this is just my test. I also changed a little bit of the code.

> cred.AADEndpoint = authSettings.Environment.ActiveDirectoryEndpoint


`
func NewAzureKeyVaultCredentialsFromClient(clientID, clientSecret, tenantID string) (*AzureKeyVaultCredentials, error) {

	authSettings, err := auth.GetSettingsFromEnvironment()
	if err != nil {
		return nil, fmt.Errorf("GetSettingsFromEnvironment err: %+v", err)
	}

	cred := azureAuth.NewClientCredentialsConfig(clientID, clientSecret, tenantID)
	cred.AADEndpoint = authSettings.Environment.ActiveDirectoryEndpoint
	cred.Resource = AzureKeyVaultResourceURI 

	return &AzureKeyVaultCredentials{
		getAuthorizer: func() (autorest.Authorizer, error) {
			authorizer, err := cred.Authorizer()
			if err != nil {
				return nil, fmt.Errorf("failed to create authorizer based on service principal credentials, err: %+v", err)
			}
			return authorizer, nil
		},
	}, nil
}
`

**Comment by mayong43111** [comment]
I create a new pull request, This is my attempt.
