### ISSUE TITLE
[BUG] could not find the requested resource (get azurekeyvaultsecrets.spv.no)

### ISSUE THREAD

**Issue by scivm** [SparebankenVest/azure-key-vault-to-kubernetes#30]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Describe the bug**
I am trying this for first time based on documentation using default auth in a test environment.  I am getting an error could not find the requested resource (get azurekeyvaultsecrets.spv.no) in the controller log.

I see that this name is part of the metadata of the Custom Resource Definition.

I think I understand better now.  The controller is created first without the crd but it wants it.  Then after installing the env injector the crd gets created so the errors stop coming from the controller?

**To Reproduce**
#!/bin/bash
RELEASE=key01
helm install $RELEASE spv-charts/azure-key-vault-controller --namespace=akv2k8s --set installCrd=false
RELEASE=key01env
helm install $RELEASE spv-charts/azure-key-vault-env-injector --namespace=akv2k8s

**Expected behavior**
No errors

**Logs**
xxshambm@WL362836:~/git/analytics-workspace/scripts$ kubectl --namespace=akv2k8s logs key01-azure-key-vault-controller-65bc586d97-p59vc
time="2020-01-18T12:03:36Z" level=info msg="Log level set to 'info'"
time="2020-01-18T12:03:36Z" level=info msg="Creating event broadcaster"
time="2020-01-18T12:03:36Z" level=info msg="Setting up event handlers"
time="2020-01-18T12:03:36Z" level=info msg="Starting AzureKeyVaultSecret controller"
time="2020-01-18T12:03:36Z" level=info msg="Waiting for informer caches to sync"
E0118 12:03:36.775250       1 reflector.go:134] github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/informers/externalversions/factory.go:120: Failed to list *v1alpha1.AzureKeyVaultSecret: the server could not find the requested resource (get azurekeyvaultsecrets.spv.no)
E0118 12:03:37.778798       1 reflector.go:134] github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/informers/externalversions/factory.go:120: Failed to list *v1alpha1.AzureKeyVaultSecret: the server could not find the requested resource (get azurekeyvaultsecrets.spv.no)
......
time="2020-01-18T12:03:58Z" level=info msg="Starting workers"
time="2020-01-18T12:03:58Z" level=info msg="Started workers"

**Additional context**

**Comment by torresdal** [comment]
Just so I understand correctly @scivm . It works now, but when the controller first started it reported errors about not finding `azurekeyvaultsecrets.spv.no`. Correct?

As you correctly resonated, the last component (the injector in this case) should have `--set installCrd=false` and not the first, which would prevent this issue.

We will update the docs. Thanks for letting us know!

Note: A new chart is developed for version 1.0 (coming soon) which will have both components (controller and injector) included and will prevent this from happening in the future.
