### ISSUE TITLE
[FEATURE/BUG?] Support for use with Bridge To Kubernetes to prevent duplicate injection

### ISSUE THREAD

**Issue by rholand3** [SparebankenVest/azure-key-vault-to-kubernetes#302]
**Is your feature request related to a problem? Please describe.**
When trying to use Bridge to Kubernetes with AKV2K8S there is an issue with duplicate volume injection. basically Bridge to kubernetes duplicates the pod description and then creates a 'duplicate' pod with different networking set up. In doing so it's copying the pod with the akv2k8s properties already injected.

**Describe the solution you'd like**
Before injecting the properties and init container into the pod description, make sure they aren't already present

**Describe alternatives you've considered**
I've tried looking into bridge to kubernetes to see if there is configuration there to prevent injected containers from being included. I'm also looking at using the secrets as env variable using valuefrom, but this is not an ideal use.

**Additional context**
![image](https://user-images.githubusercontent.com/919988/147498811-ca174cbc-8f9e-477d-9e3e-c67d3a5b3d1a.png)

**Comment by torresdal** [comment]
I'm not quite sure how to address this. Is this still an issue? If so, please re-open and we'll try to find a solution together.
