### ISSUE TITLE
Same Software for HashiCorp Vault

### ISSUE THREAD

**Issue by victorgetz** [SparebankenVest/azure-key-vault-to-kubernetes#312]
**Is your feature request related to a problem? Please describe.**
No since it works like a charm :+1: 

**Describe the solution you'd like**
Your software is just a beauty. Did you ever thought to develop it also for HashiCorp Vault?

All the current solutions for HashiCorp Vault are either not secure or very complicated to use.

I think you would also find several sponsors for it

**Comment by torresdal** [comment]
Thanks for the tip @victorgetz, but a similar solution already exist for Vault => https://github.com/banzaicloud/bank-vaults 

It's actually the one we were inspired by when creating this for AKV 😸
