### ISSUE TITLE
Replica set error after update to 2.1.0: "Service azure-key-vault-env-injector not found"

### ISSUE THREAD

**Issue by jonathaneckman** [SparebankenVest/azure-key-vault-to-kubernetes#313]
A replica set for that use akv2k8s to inject secrets is failing to create the pods with the following error:

```
Error creating: Internal error occurred: failed calling webhook
  "pods.azure-key-vault-env-injector.admission.spv.no": Post
  "https://azure-key-vault-env-injector.akv2k8s.svc:443/pods?timeout=30s":
  service "azure-key-vault-env-injector" not found
```

If see the env injector pods (in the namespace akv2k8s) are online. They write following logs when the replica set attempts to provision the pods (example command `kubectl logs -n akv2k8s akv2k8s-envinjector-7cbbfd45b6-cj75x`)

```
I0126 02:30:17.833576       1 main.go:143] "found pod to mutate" pod="my-namespace/"
I0126 02:30:17.833861       1 pod.go:285] "creating client certificate to use with auth service" my-namespace/="(MISSING)"
I0126 02:30:17.862089       1 pod.go:292] "mutate init-containers" my-namespace/="(MISSING)"
I0126 02:30:17.862114       1 pod.go:298] "mutate containers" my-namespace/="(MISSING)"
I0126 02:30:17.862123       1 pod.go:116] "found container to mutate" container="my-namespace/web"
I0126 02:30:17.862131       1 pod.go:119] "checking for env vars to inject" container="my-namespace/web"
I0126 02:30:17.862308       1 pod.go:122] "found env var to inject" env="my-secret-name@azurekeyvault" container="my-namespace/web"
I0126 02:30:17.862333       1 pod.go:122] "found env var to inject" env="my-secret-name@azurekeyvault" container="my-namespace/web"
I0126 02:30:18.377993       1 pod.go:149] "found container arguments to use for env-injector" cmd="docker-entrypoint.sh pm2-runtime npm -- start" container="my-namespace/web"
I0126 02:30:18.653205       1 pod.go:307] "containers mutated and pod updated with init-container and volumes" pod="my-namespace/"
```

My app worked fine with version 1.1.0 of akv2k8s. This issue appeared once I updated to the 2.1.0 helm chart. I did also manually update the CRDs using:

```
kubectl apply -f https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/crds/AzureKeyVaultSecret.yaml
```

Am I missing an upgrade step? Any tips on how to further troubleshoot this?

### Other things

- Uninstalling with `helm uninstall akv2k8s -n akv2k8s` then reinstalling.
- Deleting the CRD with `kubectl delete crd azurekeyvaultsecrets.spv.no` and reinstalling it.
- I'm using k8s version 1.21.7.
- I see this [in the requirements](https://akv2k8s.io/installation/requirements/) "you should at most have only one Env Injector installment in your cluster". I see only 1 **akv2k8s-envinjector** deployment with 2 envinjector pods. This seems right to me.

**Comment by tspearconquest** [comment]
The error message looks like your akv2k8s service is missing, so I would look for the output of `kubectl get svc` in the namespace where akv2k8s runs and check the helm chart for why its missing.

Note: I am not a developer here, I just wanted to try to help :)

**Comment by tspearconquest** [comment]
Voting to close due to lack of response.
