### ISSUE TITLE
[FEATURE] Re-sync period configurable 

### ISSUE THREAD

**Issue by dimuskin** [SparebankenVest/azure-key-vault-to-kubernetes#327]
We have multiple k8s clusters with dozens of domains on each. But re-sync certificates every 30 sec causes a huge load to vault and also it increases costs.  It will be good to have resync period configurable.

Best Regards.

**Comment by HenrikDK** [comment]
+1 on this, since I deployed AzureKeyVaultSecretSync object 9 days ago it has triggered 28729 update events in kubernetes, it would be really nice if these intervals were configurable pr secret.

**Comment by PsychoNineSix** [comment]
This was implemented in #371, I'm currently awaiting review on SparebankenVest/public-helm-charts#76 to allow configuring this using helm
