### ISSUE TITLE
How do we use aad-pod-identity for controllers

### ISSUE THREAD

**Issue by raushan2016** [SparebankenVest/azure-key-vault-to-kubernetes#4]
As per the aad-pod-identity, after you create the "AzureIdentity" and "AzureIdentityBinding". You need to specify the label "aadpodidbinding" from "AzureIdentityBinding" during deployment of the controller. The install step is not clear about how you do this. The helm template also does not allow this. [https://github.com/SparebankenVest/public-helm-charts/blob/019fdcc58f3bdbd5396958a3e6471632bf0b033e/stable/azure-key-vault-controller/templates/deployment.yaml](url)

Does it mean you need to change the template and set the label and then run `helm install spv-charts/azure-key-vault-controller --set keyVault.customAuth.enabled=true`

**Comment by torresdal** [comment]
You are right @raushan2016 - the helm charts currently does not support this. After we added support for using the built-in Cloud Config (`/etc/kubernetes/azure.json`), using aad-pod-identity was not prioritized (at the time we felt the process around aad-pod-identity was quite complex). We do however want to support aad-pod-identity properly, but I cannot promise anything right now. If you're able to help however, we more than welcome pull requests.

**Comment by torresdal** [comment]
This is now fixed in version `0.1.21` of the `azure-key-vault-controller` Helm chart.
