### ISSUE TITLE
[BUG] AKV2K8S environment injectors don't work with `automountServiceAccountToken: false` and bound service account volume projection configured

### ISSUE THREAD

**Issue by tspearconquest** [SparebankenVest/azure-key-vault-to-kubernetes#424]
**Note: Make sure to check out known issues (https://akv2k8s.io/troubleshooting/known-issues/) before submitting**

**Components and versions**
Select which component(s) the bug relates to with [X].

[ ] Controller, version: `x.x.x` (docker image tag)
[x] Env-Injector (webhook), version: `x.x.x` (docker image tag)
[ ] Other

**Describe the bug**
I configured AKV2K8S Environment Injectors deployment with `automountServiceAccountToken: false` and a volume + volume mount for the same with the bound service account token volume projection feature in Kubernetes 1.22. After redeploying the service, the environment injector pods start properly, but downstream services fail to start. It appears the injected command for the downstream service is trying to connect to the injectors service in the default namespace instead of the configured namespace for the akv2k8s service.

No other changes took place between the working deployment and the broken deployment.

**To Reproduce**
- Use `helm template` to generate an akv2k8s environment injector deployment manifest
- Edit the manifest to set `automountServiceAccountToken: false`
- Add a volume and volume mount configured with the bound service account token volume projection feature enabled:
    ```
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          - containers:
            volumeMounts:
            - name: env-injector
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
          volumes:
          - name: env-injector
            projected:
              sources:
              - configMap:
                name: kube-root-ca.crt
              - serviceAccountToken:
                path: token
    ``` 

**Expected behavior**
Downstream services should connect to the akv2k8s service properly and get their secrets injected

**Logs**

```
I1029 16:12:37.900467       1 version.go:31] "version info" version="" commit="" buildDate="2022-10-28T23:35:57Z" component="vaultenv"
I1029 16:12:37.900623       1 main.go:184] "azure key vault env injector initializing"
I1029 16:12:37.900839       1 main.go:253] "found original container command" cmd="/usr/local/bin/tini" args=[tini -- /fluentd/entrypoint.sh]
I1029 16:12:37.900900       1 authentication.go:98] "checking if current auth service credentials are stale" url="http://env-injector.default.svc:80/auth/fluentd/fluentd-vvtjg?secret=akv2k8s-fluentd"
I1029 16:12:37.916439       1 authentication.go:98] "checking if current auth service credentials are stale" url="http://env-injector.default.svc:80/auth/fluentd/fluentd-vvtjg?secret=akv2k8s-fluentd"
I1029 16:12:40.929579       1 authentication.go:98] "checking if current auth service credentials are stale" url="http://env-injector.default.svc:80/auth/fluentd/fluentd-vvtjg?secret=akv2k8s-fluentd"
I1029 16:12:46.943767       1 authentication.go:98] "checking if current auth service credentials are stale" url="http://env-injector.default.svc:80/auth/fluentd/fluentd-vvtjg?secret=akv2k8s-fluentd"
E1029 16:12:46.945650       1 main.go:269] "failed to get credentials" err="failed to check for stale credentials: Get \"http://env-injector.default.svc:80/auth/fluentd/fluentd-vvtjg?secret=akv2k8s-fluentd\": dial tcp: lookup env-injector.default.svc on 10.254.128.10:53: no such host" failedTimes=3
```

**Additional context**
N/A

**Comment by tspearconquest** [comment]
I suspect this is also the cause for the issue reported in one of the comments on #265 if not the cause of #265 itself.

**Comment by tspearconquest** [comment]
I figured this out. I was missing a required projection of the `downwardAPI` volume type.

The proper way to configure the `volume` spec is documented [here](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume)

An example based on my example from the OP:

```
spec:
  template:
    spec:
      automountServiceAccountToken: false
      - containers:
        volumeMounts:
        - name: env-injector
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: env-injector
        projected:
          sources:
          - configMap:
            name: kube-root-ca.crt
          - downwardAPI:
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace
          - serviceAccountToken:
            path: token
```

Hope this helps others trying to use this important feature, and hope this setup will also soon be supported in the akv2k8s helm chart. I'm going to close the issue since this isn't an AKV2K8S bug.

**Comment by prestonr83** [comment]
> I figured this out. I was missing a required projection of the `downwardAPI` volume type.
> 
> The proper way to configure the `volume` spec is documented [here](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume)
> 
> An example based on my example from the OP:
> 
> ```
> spec:
>   template:
>     spec:
>       automountServiceAccountToken: false
>       - containers:
>         volumeMounts:
>         - name: env-injector
>           mountPath: /var/run/secrets/kubernetes.io/serviceaccount
>           readOnly: true
>       volumes:
>       - name: env-injector
>         projected:
>           sources:
>           - configMap:
>             name: kube-root-ca.crt
>           - downwardAPI:
>               items:
>               - fieldRef:
>                   apiVersion: v1
>                   fieldPath: metadata.namespace
>                 path: namespace
>           - serviceAccountToken:
>             path: token
> ```
> 
> Hope this helps others trying to use this important feature, and hope this setup will also soon be supported in the akv2k8s helm chart. I'm going to close the issue since this isn't an AKV2K8S bug.

Thank you. This saved me a lot of throubleshooting.

**Comment by tspearconquest** [comment]
I'm happy I could help!
