### ISSUE TITLE
[Question] Multi-tenancy setup

### ISSUE THREAD

**Issue by jemag** [SparebankenVest/azure-key-vault-to-kubernetes#43]
**Your question**
What is the proper way to achieve a multi-tenancy setup with akv2k8s?

Basically, we have a cluster with multiple tenants, each having their own namespace. For each namespace, we would like to restrict access to the team's own keyvault (so 1 team = 1 namespace = 1 key vault access).

Currently, I am not too sure how we could best achieve this. The credentials seems to be set for the whole chart. I guess we could create multiple controller and injectors but since the webhook is triggered based on the "azure-key-vault-env-injection: enabled" label, I am guessing this would trigger all instances?

Since we cannot restrict access to specific secrets in key vault, I am not sure how to get started building a multi-tenancy setup with akv2k8s.

**Comment by torresdal** [comment]
@jemag We do not currently support multi-tenancy directly, but I believe what you are aiming for is doable with the env-injector in current model. 

1. You will have to set `customAuth.enabled=true` and not use any of the autoInject features. 
2. In each namespace/tenant create a Kubernetes secret with Service Principal credentials to use for that tenant. 
3. For each Kubernetes Deployment, use any of the Azure Auth env variables [documented](https://akv2k8s.io/security/authentication/#custom-authentication-options) by referencing values in secret created in 2.
4. Use injector as normal

This is not well tested, but should work. If not, let us know and we’ll fix it.

**Comment by jemag** [comment]
@torresdal thank you for the clarification!

It does seem to work with the method you have provided, although I did have to debug a bit since the examples from https://akv2k8s.io/stable/azure-key-vault-env-injector/README/#installing-the-chart mentionned
```
helm install spv-charts/azure-key-vault-env-injector \
  --namespace akv2k8s \
  --set customAuth.enabled=true \
  --set customAuth.autoInject.enabled=true \
  --set customAuth.autoInject.secretName=azure-key-vault-secret \
  --set env.AZURE_TENANT_ID=... \
  --set env.AZURE_CLIENT_ID=... \
  --set env.AZURE_CLIENT_SECRET=...
```
with **customAuth.enabled** instead of  **keyVault**.customAuth.enabled

The only thing that makes me feel a bit uneasy with this method is that you end up with the credentials for your service principal in clear text in the environment variables of your container. So technically, if someone managed to get access to the container, he could obtain the service principal credentials that have access to all of that given keyvault secrets. Is that not a security concern?

**Comment by torresdal** [comment]
It is, though currently the best we can do to solve your scenario. Saying that, the norm in the container world is to inject secrets through env vars. And if *“someone managed to get access to the container”* - you’re in serious trouble - and of course even more so if your vault gets compromised as well.

We are considering some ideas that probably will make this more secure in the future. 

How would you solve this in Kubernetes without akv2k8s?

(Btw - will fix the example with correct values asap)

**Comment by jemag** [comment]
@torresdal yeah to be honest I am not too sure how I would go about solving this with pure Kubernetes, without akv2k8s. I just feel like having the service principal credentials fully accessible in env variables is probably  worst than having just a couple of secrets there, because with the service principal you may get access to all the other secrets. I guess I could perhaps take a look at https://github.com/Azure/kubernetes-keyvault-flexvol or HashiCorp Vault integrations.

To be honest, I have been using akv2k8s for a decently long time now and it was fulfilling our single tenant clusters use-case nicely until we've had the requirement to move into multi-tenancy clusters.

Would having multiple instances of akv2k8s and providing each of them with a specific label to trigger on and specific service principal credentials be a possibility? Maybe I am totally off base here, but it seems like that could work without too much modification to the current code base, since it would mostly be about modifying how to provide a specific trigger label?

**Comment by torresdal** [comment]
Closing this for now. In the future I will not rule out multi tenancy support using typically using the operator pattern, but not supported out of the box today.
