### ISSUE TITLE
[FEATURE] reverse sync: upload k8s secrets into azure keyvault

### ISSUE THREAD

**Issue by crabcz** [SparebankenVest/azure-key-vault-to-kubernetes#434]
**Is your feature request related to a problem? Please describe.**
We are already happy to use akvk8s to sync secrets from keyvault to k8s, but for one project, we need to be able to generate TLS certificates with letsencrypt using HTTP challenge with cert-manager. The problem is, that our TLS termination happens at an Azure Application gateway and we need to transport the certificate back to azure keyvault in order to use it by the gateway.

Since we already have the akv2k8s chart in the cluster with access to both k8s secrets AND access to keyvault, it would just be more convenient to use one tool for sync

**Describe the solution you'd like**
A flag which will reverse sync direction of secret 

**Describe alternatives you've considered**
We can use k8s cronjob to periodically sync the generated cert-manager to Azure, but since we already have akv8ks installed, it would be very convenient and will reduce the need to manage separately access credentials

**Comment by Olsenius** [comment]
When I looked into certs for app gateway (about a year ago) the best solution i found was https://github.com/shibayan/keyvault-acmebot and https://github.com/shibayan/terraform-azurerm-keyvault-acmebot.

Its a function that get certs and puts them in a key vault. Not 100% scriptable, but once it is set up you dont have to fiddle much with it.

**Comment by tspearconquest** [comment]
This sort of functionality can pose a security risk in that currently, AKV2K8S only needs permissions `Get` and `List` on the keyvault access policy, but having the ability to push would require granting additional privileges. Since AKV does not permit limiting what secret can be written, any compromise of AKV2K8S could theoretically lead to arbitrary update of any secret in Keyvault.

It is a nice idea, but I think out of scope for AKV2K8S. Maybe if you want, a separate package could be published called K8S2AKV? 😅

**Comment by torresdal** [comment]
Hi @crabcz. This is unfortunately not within the feature scope of akv2k8s. One reason is as @tspearconquest mentions regarding security. The other being we're trying to keep akv2k8s as simple as possible solving only the initial 3 problems it was set out to solve (see https://akv2k8s.io):

1. Avoid a direct program dependency on Azure Key Vault for getting secrets, and adhere to the 12 Factor App principle for configuration (https://12factor.net/config)

2. Make it simple, secure and low risk to transfer Azure Key Vault secrets into Kubernetes as native Kubernetes secrets

3. Bypass using Kubernetes Secrets entirely and transparently inject Azure Key Vault secrets directly into container applications
