### ISSUE TITLE
[BUG] Certificate with bundle in wrong order

### ISSUE THREAD

**Issue by AlexBevan** [SparebankenVest/azure-key-vault-to-kubernetes#46]
**Describe the bug**
On trying to use akv2k8s with the nginx-ingress controller had the following error:

Error obtaining X.509 certificate: unexpected error creating pem file: tls: private key does not match public key.

On investigation I could see akv2k8s was putting my crt below the bundle rather than on top. 

**To Reproduce**
PFX certificate with bundle in KV, try to export as as type certificate.

**Expected behavior**
Certificate and bundle should be in the correct order

**Comment by torresdal** [comment]
@AlexBevan thanks for reporting this. However, I did some testing and also added a test case in the test suite for this specific case, and I cannot duplicate the behavior you describe. Are you 100% sure your PFX has the certs in correct order? You can verify this using openssl:

`openssl pkcs12 -in mydomain.com.pfx -nodes`

**Comment by chelnak** [comment]
Just came on to post an issue about this. We have the same problem but with Traefik. Our certificate requests and fulfillment are automated through source control so we do not have any manual interaction with the process.

When examining the certificate the chain is in the following order:
1. Intermediate
2. Root
3. Server

It looks like the certificate is also in this order in KV.

@AlexBevan are you minting certificates this way?

**Comment by torresdal** [comment]
Just to clearify @chelnak - when you say *examining the certificate* you mean with openssl (or similar) or the end output in Kubernetes?

By definition ([RFC4346](http://tools.ietf.org/html/rfc4346#section-7.4.2)) a chain should:

```
The sender's certificate must come first in the list.
Each following certificate must directly certify the one preceding it.
```

**Comment by torresdal** [comment]
In case you want to have a look at the code, and maybe see something I don't, here's the relvant sections:

In the Controller: [/cmd/azure-keyvault-controller/controller/secret_handler.go#L154](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/f2550fc147fc0a7f844328304fa130f8a5acfae6/cmd/azure-keyvault-controller/controller/secret_handler.go#L154)

In the akv service: [/pkg/azurekeyvault/client/azure_keyvault_service.go#L137](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/f2550fc147fc0a7f844328304fa130f8a5acfae6/pkg/azurekeyvault/client/azure_keyvault_service.go#L137)

Creating cert from pfx: [/pkg/azurekeyvault/client/certificate.go#L76](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/f2550fc147fc0a7f844328304fa130f8a5acfae6/pkg/azurekeyvault/client/certificate.go#L76)

Exporting public keys as pem: [/pkg/azurekeyvault/client/certificate.go#L141](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/f2550fc147fc0a7f844328304fa130f8a5acfae6/pkg/azurekeyvault/client/certificate.go#L141)

**Comment by chelnak** [comment]
Hey @torresdal , that's a yes to both. Checking the cert directly from Key Vault and from the k8s secret gives me the results I posted above.

Thank you for the code refs. Myself and a colleague had previously looked through and couldn't see anything obvious. I'll take another look now though as I could have been looking in the wrong place 👍 

I did wonder if this was actually to do with the way that the certificates are minted in Key Vault.. which is why I was interested in @AlexBevan 's flow.

Thanks for replying!

**Comment by AlexBevan** [comment]
I diffed the secrets from K8S, comparing a secret I knew was working to the one generated by akv2k8s.

I've been playing with Go. but very much a newbie so the code is a bit over my head sorry!

**Comment by AlexBevan** [comment]
> @AlexBevan thanks for reporting this. However, I did some testing and also added a test case in the test suite for this specific case, and I cannot duplicate the behavior you describe. Are you 100% sure your PFX has the certs in correct order? You can verify this using openssl:
> 
> `openssl pkcs12 -in mydomain.com.pfx -nodes`
> 
> Is the output of the open ssl command different from the pem-chain in Kubernetes?

Yes, the chain is in the wrong order here when i run `openssl pkcs12 -in mydomain.com.pfx -nodes`, we don't have control of how the PFX is created, I guess this is the default order azure app service certificates generates them?

**Comment by chelnak** [comment]
It would appear that the default KV order goes against the RFC then? Unless i'm missing something.

@AlexBevan Re your bash script - are you not using PFX directly with Akv2k8s?

**Comment by AlexBevan** [comment]
The script was my process to get the crt and key value for my k8s tls secrect. trying to replace it with ...

```
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: certificate-sync 
  namespace: mynamespace
spec:
  vault:
    name: nameofmykevault
    object:
      name: azure-app-services-generated-cert
      type: certificate
  output: 
    secret:
      name: aks-ingress-tls
      type: kubernetes.io/tls 
```

**Comment by torresdal** [comment]
Looks like this is a weird MS thing. Seams to be the same issue in PowerShell: https://www.reddit.com/r/PowerShell/comments/905w3d/exportpfxcertificate_incorrect_certificate_chain/

If the ordering of PFX certs exported from AKV always have the same pattern (n,0,1,2...), we can re-order on our side. This is a bit risky though, as some user may rely on the wrong order 🙈 I'm thinking we could introduce a setting somewhere, but right now it's not obvious where... thinking...

**Comment by AlexBevan** [comment]
Can you output the chain and crt separately as per my bash example?

**Comment by chelnak** [comment]
@torresdal What about something like this..

```
.....
  output: 
    secret:
      name: aks-ingress-tls
      type: kubernetes.io/tls 
      chainOrder: ensureserverfirst 
```

`chainOrder` could have the values:
* ensureserverfirst - ensure ordering is (n,0,1,2...) for scenarios like this
* default - do nothing

**Comment by torresdal** [comment]
@chelnak Not a bad idea at all. I’ll have a go at it, unless someone else is dying to create a pull request for it? Hopefully it’s a quick fix. Thanks!

**Comment by chelnak** [comment]
I’d love to try and implement something. My main issues are time and not being a go dev!

I’ll have a go at getting a local dev env set up.

**Comment by masenius** [comment]
Hi, just ran in to this issue myself. Did anyone start to create a PR?

**Comment by torresdal** [comment]
Not that I’m aware of...

**Comment by chelnak** [comment]
I’d planned to give it a go but the recent events have delayed that a bit!

**Comment by masenius** [comment]
Ok! I also have no control of the certificate generation. In my case the order is:

1. Root

**Comment by masenius** [comment]
Alright, I think I have a working solution now. I'll come in with a pull request tomorrow, I need to do some cleanup and update the documentation.

**Comment by jonhoare** [comment]
Interestingly I am having a similar issue but my certificates appear to be in the order of...
