### ISSUE TITLE
[Question] Support for USGov Cloud?

### ISSUE THREAD

**Issue by jeffwmiles** [SparebankenVest/azure-key-vault-to-kubernetes#472]
**Your question**
Does Akv2k8s support more Azure clouds than just `AzurePublicCloud`? 

I found https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/28 which links to a merged commit that seems to add a parameter for `AZURE_ENVIRONMENT`, however doing a code search in this repository doesn't seem to have any match to that pull request from 2020. 

Is it possible to supply a configuration setting to choose the Azure Cloud, and thus have the correct KeyVault URI used?

**Comment by 181192** [comment]
Hi @jeffwmiles should be possible using the AZURE_ENVIRONMENT variable that gets passed to the azure client provider

**Comment by jeffwmiles** [comment]
Thanks for the response @181192; I'll give that a try. I see that env variable referenced in other isssues (such as #417) however I can't find any uses within the source, or the public documentation which has caused my confusion.
