### ISSUE TITLE
[Question] Controller polling interval 

### ISSUE THREAD

**Issue by constantinmuraru** [SparebankenVest/azure-key-vault-to-kubernetes#505]
**Your question**
In the docs [1] in says that the _Controller periodically polls Azure Key Vault for changes and applies to the Kubernetes Secret or ConfigMap_. Any idea what this period is and if it can be configured?

[1] https://akv2k8s.io/how-it-works/

**Comment by 181192** [comment]
Hi @constantinmuraru :relaxed: , you can controll the resync period by changing the k8s informer listener interval using `azureKeyVaultResyncPeriod` default is every 30 sec.
 https://github.com/SparebankenVest/public-helm-charts/blob/af0975742971d80f846225230cf940a5bb859210/stable/akv2k8s/values.yaml#L58-L61
