### ISSUE TITLE
[Question] Are unknown azure clouds supported?

### ISSUE THREAD

**Issue by devhl-labs** [SparebankenVest/azure-key-vault-to-kubernetes#523]
Using the environment variable AZURE_ENVIRONMENT we can select the cloud such as these:

AzureCloud
AzureChinaCloud
AzureUSGovernment
AzureGermanCloud

But these are not the only clouds. There are others that the az cli does not know by default. Is there a way to use this an a cloud other than those listed above?

**Comment by tspearconquest** [comment]
Hi! Not sure of the context here, but AKV2K8S will use the cloud config from the node, so it should (theoretically) support any Azure Cloud that is offered by Microsoft.

**Comment by 181192** [comment]
Using the environment method you can pass all allowed AZURE_ENVIRONMENT values that the Azure go client support. Also we fixed using correct DNS against keyvault in such scenarios #524
