### ISSUE TITLE
[BUG] Installed with helm, CrashLoopBackOff

### ISSUE THREAD

**Issue by eschbach-dd** [SparebankenVest/azure-key-vault-to-kubernetes#546]
**Note: Make sure to check out known issues (https://akv2k8s.io/troubleshooting/known-issues/) before submitting**

**Components and versions**
Select which component(s) the bug relates to with [X].

[x] Controller, version: `x.x.x` (docker image tag)
[ ] Env-Injector (webhook), version: `x.x.x` (docker image tag)
[ ] Other

**Describe the bug**
![image](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/assets/134583607/97605ef4-a6e3-4673-966e-2edc2b2d0d5a)
![image](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/assets/134583607/4a579228-e4ec-4c42-a785-9f4e874280fb)

**To Reproduce**
I followed the instructions to setup using help. But I applied it with terraform:
```
resource "helm_release" "akv2k8s" {
  name             = "akv2k8s"
  repository       = "https://charts.spvapi.no"
  chart            = "akv2k8s"
  create_namespace = true
  namespace        = "akv2k8s"
  version          = "2.3.5"
}
```

**Logs**
If applicable, add logs to help explain your problem.

```
I0605 14:07:45.565698       1 main.go:103] "log settings" format="text" level="2"
I0605 14:07:45.565742       1 version.go:31] "version info" version="1.4.0" commit="15d87b2" buildDate="2022-12-08T21:18:59Z" component="controller"
W0605 14:07:45.566001       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0605 14:07:45.566748       1 main.go:168] "Creating event broadcaster"
I0605 14:07:45.576709       1 controller.go:167] "setting up event handlers"
I0605 14:07:45.576791       1 controller.go:178] "starting azurekeyvaultsecret controller"
I0605 14:07:45.676969       1 controller.go:196] "starting azure key vault secret queue"
I0605 14:07:45.677018       1 controller.go:199] "starting azure key vault deleted secret queue"
I0605 14:07:45.677038       1 controller.go:202] "starting azure key vault queue"
I0605 14:07:45.677054       1 controller.go:205] "started workers"
I0605 14:08:10.874449       1 worker.go:61] Shutting down DeletedAzureKeyVaultSecrets Queue
I0605 14:08:10.874492       1 worker.go:61] Shutting down AzureKeyVaultSecrets Queue
I0605 14:08:10.874501       1 worker.go:61] Shutting down AzureKeyVault Queue
I0605 14:08:10.874514       1 controller.go:207] "Shutting down workers"
```

Even debug logs don't say much. Looks like it's restarting because the livenessprobe fails.

**Comment by franrebo84** [comment]
Same issue here, upgrading from helm chart 2.1.0.

**Comment by EnricoOr** [comment]
It is a [problem](https://github.com/SparebankenVest/public-helm-charts/issues/97) of the helm chart 2.3.5. Probes where added but as you can see from the controller main.go code, the probe endpoint is dependant from the metric server so the endpoint is available only with the metric server enabled. The current workaround is to enable the metric server in your values.yml or downgrade your chart version.

**Comment by kenny-y-dev** [comment]
As a workaround I was able to get the controller to a stay up by adding the config option inline to the helm install command with `helm upgrade --install akv2k8s spv-charts/akv2k8s --set global.metrics.enabled=true  --namespace akv2k8s`

**Comment by iamraj007** [comment]
> As a workaround I was able to get the controller to a stay up by adding the config option inline to the helm install command with `helm upgrade --install akv2k8s spv-charts/akv2k8s --set global.metrics.enabled=true --namespace akv2k8s`

Above given solution works fine and make akv2k8s working again, but this is a **manual** step after helm... 
Can someone please fix this as its breaking automation and trust both, please.  

@torresdal  
@181192

**Comment by EnricoOr** [comment]
> Thanks for your info. Which chart version should work?

any previous version should work fine since the template for the controller doesn't include the probes

**Comment by tspearconquest** [comment]
> Above given solution works fine and make akv2k8s working again, but this is a **manual** step after helm... Can someone please fix this as its breaking automation and trust both, please.

It's not a manual step that you have to do after helm. You can add this to values.yaml:

```
global:
  metrics:
    enabled: true
```
