### ISSUE TITLE
[Question] Any plans to replace gorilla

### ISSUE THREAD

**Issue by tspearconquest** [SparebankenVest/azure-key-vault-to-kubernetes#565]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Your question**
Any plans to replace gorilla?

https://github.com/gorilla/mux/issues/659

**Additional context**
The project was archived in December 2022. Issues to report CVEs cannot be opened, therefore unknown CVEs could exist and it is highly recommended to replace gorilla with something else.

Some alternatives are listed in some other issues I found on github:

- https://github.com/weaveworks/common/issues/272
- https://github.com/edgexfoundry/edgex-go/issues/4247#issuecomment-1401262960

**Comment by cgroschupp** [comment]
https://gorilla.github.io/blog/2023-07-17-project-status-update/

**Comment by 181192** [comment]
Closing for now project active again https://github.com/gorilla/mux/pull/713
