### ISSUE TITLE
[Question] Use of akv2k8s-controller-reader & akv2k8s-controller-reader cluster role

### ISSUE THREAD

**Issue by opendba** [SparebankenVest/azure-key-vault-to-kubernetes#580]
**Your question**
We are using akv2k8s in a controller mode on AWS EKS (env_injector.enabled=false). During security review, we have noticed that upon akv2k8s installation cluster role "akv2k8s-controller-reader" is created that gives default service account r/o access to azurekeyvaultsecrets resource.
By checking the source code and documentation it's not clear why this global role is needed. In a controller mode we rely on the akv2k8s controller to sync secrets between azure and kubernetes, there is no akv2k8s related workload or sidecars running inside the other namespaces, so in my opinion that cluster role is not needed. 
Could you please confirm it's safe to drop "akv2k8s-controller-reader" and appropriate cluster role binding.

This is the helm chart responsible for creating reader role: https://github.com/SparebankenVest/public-helm-charts/blob/master/stable/akv2k8s/templates/controller-rbac.yaml#L54

**Comment by tspearconquest** [comment]
Do you have an "AzureKeyVaultSecret" resource in your other namespaces (`kubectl get azurekeyvaultsecret -n <other_namespace>`)?

**Comment by tspearconquest** [comment]
It looks safe to remove IMO. I would try to remove it on a non-prod cluster and restart akv2k8s and a few workloads relying on the synced secrets. If nothing breaks, then it should be safe.

**Comment by tspearconquest** [comment]
Understood, and I agree, it doesn't appear to be needed. I'll open a pull request to remove this; I'm not one of the maintainers but I'll ping them in slack to ask for a review once it's open. Thanks for raising this.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
