### ISSUE TITLE
[FEATURE] Vault name from configmap or secret

### ISSUE THREAD

**Issue by kaktuspalme** [SparebankenVest/azure-key-vault-to-kubernetes#60]
I would like to inject the key vault name from a secret or configmap value.

In our case we have several AzureKeyVaultSecrets pointing to the same keyvault. Then we also have multiple clusters and so I have to manually edit the keyvault name and apply it manually to every cluster.

So I would like to preconfigure the key vault name in a secret or configmap value. Then I could apply the same yaml files without any additional configuration to all clusters. Also in case of adding a new value I could just rollout the new yaml without defining all the different keyvaults again.

**Comment by torresdal** [comment]
Secrets and configmaps are namespace bound, so you would have to create secret/configmap for every namespace. 

Compared to other native kubernetes objects, this would be the same as loading name of a deployment from a configmap. This is not common practice. I suggest you look at using templating for your requirement.

**Comment by kaktuspalme** [comment]
Thanks for your response and suggestion. I already use helm templates and values file if that's what you meant by using templates.

But that doesn't really solve the problem. I still have to adjust the values when applying the template on every cluster.

If you have a running service which depends on a secret. Later you have to add another secret, how do you update all the clusters with the new secret?

But I know it's probably an edge case.

**Comment by torresdal** [comment]
I don't think we will support this in akv2k8s. When I mentioned templating, I was thinking more about [Kustomize](https://github.com/kubernetes-sigs/kustomize). We use it to handle different values for different environments, and I believe you could use it to name your AzureKeyVaultSecret's.

**Comment by kaktuspalme** [comment]
Probably I can solve it with Lookup Functions introduced in Helm 3.1.
