### ISSUE TITLE
[Question] When will a version that resolves https://github.com/advisories/GHSA-45x7-px36-x8w8 be released?

### ISSUE THREAD

**Issue by chris-kennedy** [SparebankenVest/azure-key-vault-to-kubernetes#675]
My services are being flagged for [GHSA-45x7-px36-x8w8](https://github.com/advisories/GHSA-45x7-px36-x8w8) which is resolved by https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/pull/655.

Even knowing a target date for a release would be helpful.

Thanks!

**Comment by lmqt890930** [comment]
also hope to know
