### ISSUE TITLE
[FEATURE] Configurable az cloud (e.g. AzureChinaCloud)

### ISSUE THREAD

**Issue by astromoose** [SparebankenVest/azure-key-vault-to-kubernetes#74]
**Is your feature request related to a problem? Please describe.**
`akv2k8s` Running in the *AzureChinaCloud* cloud uses the global endpoint for `keyvaultDns`.

```
$ az cloud show --name AzureCloud --output json | grep keyvault
    "keyvaultDns": ".vault.azure.net",
$ az cloud show --name AzureChinaCloud --output json | grep keyvault
    "keyvaultDns": ".vault.azure.cn",
```

**Describe the solution you'd like**
It would be great to be able to configure the Azure cloud you are running `akv2k8s` in. I bet users of the *AzureGermanCloud* would love this too.

**Describe alternatives you've considered**
Spinning up an akv instance in the global Azure cloud for a project running in China. Then configuring additional custom auth for it?

**Comment by masterphenix** [comment]
Hello,
What you are looking for already seems to exist, you just have to specify the AZURE_ENVIRONMENT variable :
``` 
helm install spv-charts/azure-key-vault-controller \
  --namespace akv2k8s --set env.AZURE_ENVIRONMENT=AzureChinaCloud
helm install spv-charts/azure-key-vault-env-injector \
  --set installCrd=false  --namespace akv2k8s  --set env.AZURE_ENVIRONMENT=AzureChinaCloud

**Comment by astromoose** [comment]
Excellent, thanks! 👍
