### ISSUE TITLE
[Question] Pull secret from different namespace

### ISSUE THREAD

**Issue by lemonprogis** [SparebankenVest/azure-key-vault-to-kubernetes#77]
Hello, first, thanks for this great project. We are evaluating using this to use with the env injector sidecar and have come across something that we just can't figure out yet. 

In the CRD, we state the namespace while defining a AzureKeyVaultSecret. Is it possible to use this defined AzureKeyVaultSecret in another namespace? If so, how to accomplish this?

Thank you!

**Comment by dstrimble** [comment]
Yes, it would be great if I could put all of my key references in the main namespace where the injector is installed and then reference them from any namespace so that I don't have to put the CRD instance in every namespace.

**Comment by lemonprogis** [comment]
Just checking out through the code and was wondering if this would be the right path. 

https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/pull/78/commits/bdb1d0e45d437d8fb5a27af28ac221b8e8e6a30e

**Comment by torresdal** [comment]
@lemonprogis  Not sure I follow. Following common Kubernetes practices, AzureKeyVaultSecret behaves as Kubernetes Secret does. You cannot reference secrets across namespaces.
