### ISSUE TITLE
[Question] How does this compare to Azure Key Vault provider for Secret Store CSI driver

### ISSUE THREAD

**Issue by hansmbakker** [SparebankenVest/azure-key-vault-to-kubernetes#84]
**Your question**
When first taking a dependency on a tool / library / component, I always assess a bit what functionality it offers, how actively it is developed, etc.
Your add-on for Kubernetes looks useful as Keyvault is not integrated natively with AKS. However I see there are multiple tools that offer this functionality - besides your one, there is also https://github.com/Azure/secrets-store-csi-driver-provider-azure.

Reading https://mrdevops.io/introducing-azure-key-vault-to-kubernetes-931f82364354, I understood that you didn't want applications taking a dependency on Keyvault themselves, but I could not find whether this library distinguishes itself in some form from the others.

Could you please say something about that?

**Comment by torresdal** [comment]
From what I can assess after a quick view at the CSI driver, the main difference from my perspective is that the CSI driver expose external secrets (AKV in this case) through kubernetes volumes, while akv2k8s sync to native kubernetes secrets (controller) or transparently inject secrets into applications (env-injector). I guess it's a matter of preference if you want your secrets as volumes or not. 

When we developed the akv2k8s project, we had an additional requirement that prevented us from using tools like the CSI driver: the secret content should not be visible in Kubernetes (not in file, disk or memory) - it should be directly injected through a env-variable into to program running inside a container. This is what the env-injector does.

**Comment by hansmbakker** [comment]
Thank you for the explanation and rationale!
