### ISSUE TITLE
[BUG] or Issue: Impossible to Inject a Secret as per https://akv2k8s.io/tutorials/env-injection/1-secret/

### ISSUE THREAD

**Issue by gopher194** [SparebankenVest/azure-key-vault-to-kubernetes#89]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Describe the bug**
While deploying and using the Tutorial, the sync'ing of secrets works, but the injection of the secret fails. We tried customAuth, AadPod Identity, Kubenet & CNI, Service Principal, deploying/destroying/redeploying AKS clusters, no way to make it work

**To Reproduce**
Deploy an AKS Cluster: k8s version: 1.16.9, Service Principal Identity, Private AKS cluster, outboundType: UDR, a Key Vault with Private endpoint, give get secret access policy permission to the AKS Service Principal in Key Vault.

Images used: Controller: 1.1.0-beta.4, Webhook: 1.1.0-beta.24, Env: 1.1.0-beta.24

Deploy: https://akv2k8s.io/tutorials/sync/1-secret/ It works!

Deploy: https://akv2k8s.io/tutorials/env-injection/1-secret/ you get this log:
`kubectl.exe logs -n akv2k8s-test akvs-secret-app-6d945f66dc-cw8rv`
`secret-inject@azurekeyvault`
`waiting forever...`

**Expected behavior**
The logs to display
`<The value of the secret from Key Vault>`

**Logs**
`kubectl logs akv2k8s-injector-56fdbf5f89-pqrpk`
`initializing config...`
`config initialized`
`2020/06/11 01:46:54 [WARN] no metrics recorder active`
`2020/06/11 01:46:54 [WARN] no tracer active`
`time="2020-06-11T01:46:54Z" level=info msg="listening on :443"`
`2020/06/11 01:48:03 [DEBUG] reviewing request e8513937-71c2-4714-963f-621810519ebf, named: akv2k8s-test/`
`time="2020-06-11T01:48:03Z" level=info msg="found pod to mutate in namespace 'akv2k8s-test'"`
`time="2020-06-11T01:48:03Z" level=info msg="found container 'akv2k8s-env-test' to mutate"`
`time="2020-06-11T01:48:03Z" level=info msg="checking for env vars containing '@azurekeyvault' in container akv2k8s-env-test"`
`time="2020-06-11T01:48:03Z" level=info msg="found env var: secret-inject@azurekeyvault"`
`time="2020-06-11T01:48:03Z" level=info msg="did not find credentials to use with registry 'spvest' - getting default credentials"`
`time="2020-06-11T01:48:03Z" level=info msg="registry host 'spvest' is not a acr registry"`
`time="2020-06-11T01:48:03Z" level=info msg="pulling docker image docker.io/spvest/akv2k8s-env-test:2.0.1 to get entrypoint and cmd, timeout is 120 seconds"`
`2020/06/11 01:48:03 [ERROR] admission webhook error: failed to get auto cmd, error: failed to pull docker image 'docker.io/spvest/akv2k8s-env-test:2.0.1', error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Additional context**
Same issue when pulling from an ACR, same issue with Managed Identity and Aad Pod Identity.
We use a Key Vault Private endpoint, but getting the Controller to work, makes us believe it is not relevant.
SSH in the nodes show availability and content of `/etc/kubernetes/azure.json`. However, it requires sudo level.

Any help welcome, we like a lot akv2k8s. Thanks.

**Comment by torresdal** [comment]
Thanks for reporting this. Sorry to hear this does not work. I'm confident it has worked (and IS working in our clusters), so we need to dig into some details and get back to you.

**Comment by gopher194** [comment]
Thanks Jon. I tested this morning with a "more vanilla / less restricted" cluster and got it to work. The main differences from the one not working are: outboundType UDR, Private Cluster enabled, Service Principal (instead of Managed Identity). I'll continue eliminating the settings that works from the ones that doesn't. How can I help your digging?

**Comment by torresdal** [comment]
@gopher194 if you could identify any of the diffs mentioned that would be great! We can then dig into code a figure out why it misbehaves... For the record, our testing happens in public clusters with no outgoing network restrictions, so this might be a clue. As per the error you report, it basically says it can't connect to the public docker repo - but there can be numerous reasons for that... Right now I cannot see that SP vs MI should come into play here. My bet is on routing... try running a pod with docker client and see if you can pull the image?

**Comment by gopher194** [comment]
Hello Jon. We identified a first source of issues: we use local Helm charts to deploy. Downloading them from `https://github.com/SparebankenVest/public-helm-charts/tree/master/stable` was not successful.
We actually ended up using these commands to get the right Helm Charts locally:
`helm repo add spv-charts http://charts.spvapi.no`
`helm repo update`
`helm pull spv-charts/azure-key-vault-crd --untar`
`helm pull spv-charts/azure-key-vault-controller --untar`
`helm pull spv-charts/azure-key-vault-env-injector --untar`
Then deploying them with Terraform and testing both controller and injector gave us success.

Now we will test: the pull of the 3 images from an internal Container Registry.
After that, we will start to test restricted egress and outboundType=UDR effects.

I'll post our results as soon as we have them.
Thanks for your attention on this issue.

**Comment by gopher194** [comment]
As a side note, we deploy/manage everything Azure with Terraform. So, for AKS k8s components, we decided to use Helm charts (& the helm Terraform provider) for all k8s artifacts that have CRDs.
We created 2 simple Helm charts for both secrets sync and injection.
We will share them when finished and tested.

**Comment by gopher194** [comment]
Ok, so here are the details: All works in locked down, Private links (AKS + Key Vault), restricted egress environment, with an AKS Service Principal.
When switching to a Managed Identity, the Controller works, but the Injection in Pod fails somewhere in the side container injection:
The `azure-key-vault-env-injector` pods log exactly the same processing for both SP and MSI.
But in the test pod (based on `spvest/akv2k8s-env-test:2.0.1`), the process stops here:
`time="2020-06-12T16:11:42Z" level=info msg="found original container command to be /usr/local/bin/entrypoint.sh [entrypoint.sh TEST_SECRET]" application=env-injector component=akv2k8s custom_auth=true namespace=akv2k8s-test`

It is supposed to do this next, and it doesn't:
`time="2020—06—11T13:25:07Z" level=info msg="secret ***** injected into evn var TEST_SECRET for executable /usr/local/bin/entrypoint.sh" application ...`
`time="2020—06—11T13:25:07Z" level=info msg="starting process /usr/local/bin/entrypoint.sh [entrypoint.sh TEST_SECRET] with secrets in env vars" ...`
`This is the value of the Secret pulled from Key Vault` 
`waiting forever... `

Any chance that upgrading the versions would fix that?
Here are the images used:
`azure-keyvault-controller: Image: spvest/azure-keyvault-controller:1.0.2`
`azure-key-vault-env-injector: Image: spvest/azure-keyvault-webhook:1.0.2`
`AZUREKEYVAULT_ENV_IMAGE: spvest/azure-keyvault-env:1.0.2`

Thanks.

**Comment by googol** [comment]
Has there been any development on this bug?

**Comment by torresdal** [comment]
@googol This will be supported in the upcoming 1.1 version. Ref #110

**Comment by googol** [comment]
Thanks for your response @torresdal, looking forward to the new version!

**Comment by tspearconquest** [comment]
Hello @googol and @gopher194 

I was googling to find out if AKV2K8S works with Private Endpoints configured on the Keyvault. I see you mentioned Private Endpoint in your original post, and Private Links in [this comment](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/89#issuecomment-643372625) 

So I wanted to reach out to ask which service you're using, as they are separate services in Azure. I appreciate it if you can help me to clarify this, as we're looking to disable public access entirely. We're currently using Virtual Network Rules but have already configured the Private Endpoint and so far it is working but I am hesitant remove the virtual network rule and set the Keyvault access to completely private at this point.
