### ISSUE TITLE
Feature Request: Pull all Secrets

### ISSUE THREAD

**Issue by pnda489** [SparebankenVest/azure-key-vault-to-kubernetes#9]
Hi Guys!

**Thanks for this awesome project!** 
I hope this is the right place for this Request.

I have an additional Use-Case which I want to explain to you.

We are transforming from Azure App Service with Managed Identity to Azure Kubernetes Service.

In our Microservice scenario, every service got an Azure Key Vault. Containing the secrets needed to run the service. The Service starts and pulls ALL Secrets into it as env variables.
_There might be a better approach, where the Secrets are only pulled for the time needed and then dismissed._

Currently, the AppService can connect through the Managed Identity. Now, in Kubernetes, there is no managed identity. One easy solution what it to create a Service Principal and give and create a Secret for the Pod with the credentials.

What I would like to do is the following:
Use your Env - Controller with specific Service Principal to access the Key Vault and then pulling out all Secrets into Kubernetes Pod.
This would be a greater abstraction between Secrets and Service.

So as a new Secret for a given Service comes up, I just have to add it to the Key Vault. The Env - Controller will pulled it out once the Pod restarts.

Specifying all Secrets manually per Pod/Deployment is sadly not an option for us.

Feature:
1. Pull out all secrets from Keyvault
2. Pull out all Certs

Thanks a lot,
Michael

**Comment by torresdal** [comment]
We’ve thought about this @pnda489 - sorry for being so late to respond - and decided not to support this as of now. We plan to support #36 - but that does not solve your case.

**Comment by torresdal** [comment]
Closing for now.
