### ISSUE TITLE
[FEATURE] Add support for creating a Docker pull secret

### ISSUE THREAD

**Issue by triplebeta** [SparebankenVest/azure-key-vault-to-kubernetes#90]
I would love to store my Docker image pull secret in a KeyVault and use AzureKeyVaultToKubernetes to sync it into a secret in a namespace. For some reason that does not work.

To compose a dockerconfigjson string I used the following command:
`kubectl create -n "$k8snamespace" secret docker-registry $AcrSecretName --dry-run=true  --docker-username=$dockerPullServicePrincipalAppId --docker-server=$AcrAddress --docker-password=$dockerPullPassword -o jsonpath='{.data.\.dockerconfigjson}'`

The output was inserted into a secret in my KeyVault, named MyDockerPullSecret and it contains a plain string similar to this one:
`eyJh3RocyI6eyJ0cmlwbGViZXRhLmF6Da8dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJBQUEiLCJwYXNzd29yZCI6IjsxjSIsImVtYWlsIjoiU2VydmljZVByaW5jaXBhbEBBenVyZVJNIiwiY4TVE9PSJ9fX0=`

I deploy the resource to my default namespace using this yaml:
`apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: dockerimagepullsecret
spec:
  vault:
    name: myVault
    object:
      name: MyDockerPullSecret
      type: secret
  output:
    secret: 
      name: mypullsecret
      dataKey: .dockerconfigjson
      type: kubernetes.io/dockerconfigjson
`

When I do so, the log shows the following error:
`msg="error syncing 'default/dockerimagepullsecret11': Secret \"mypullsecret\" is invalid: data[.dockerconfigjson]: Invalid value: \"<secret contents redacted>\": invalid character 'e' looking for beginning of value, requeuing"`

That "e" is the first character of the secret, as you can see. If I change the first character of the secret, I get that different value.

**Comment by torresdal** [comment]
Hi @triplebeta,

I think the secret i AKV should not be the base64 encoded string, but the actual json. Akv2k8s will then convert the json into the base64 encoded string. Not a good error description I agree. Try this and let us know? 

Example json:
‘‘‘
{
  "auths": {
    "docker.io": {
      "username":"myuser",
      "password":"mypass",
      "email":"myemail@domain.com",
      "auth":"bXl1c2VyOm15cGFzcw=="
    }
  }
}
‘‘‘

**Comment by torresdal** [comment]
Closing for now. Please reopen if suggested solution does not work.
