### ISSUE TITLE
[BUG] Secret not injected to every pod in deployment

### ISSUE THREAD

**Issue by agarwalarjun123** [SparebankenVest/azure-key-vault-to-kubernetes#92]
Issue
Secret is not getting injected to every pod in the deployment.

Ideal Scenario
It should get injected into every pod in the deployment.

Screenshots:

![Pod where it gets injected](https://i.ibb.co/jM4L3kL/Screenshot-from-2020-06-24-17-14-32.png)
![Pod where it does not get injected](https://i.ibb.co/yq9YJQx/Screenshot-from-2020-06-24-17-14-46.png)

**Comment by playersons** [comment]
please paste proper log extract, the screenshots are impossible to read.

**Comment by playersons** [comment]
> Issue
> Secret is not getting injected to every pod in the deployment.
> 
> Ideal Scenario
> It should get injected into every pod in the deployment.
> 
> Screenshots:

please paste proper log extract, the screenshots are impossible to read.

**Comment by torresdal** [comment]
@agarwalarjun123 agree with @playersons - please submit logs in text and we'll be happy to help. Closing.
