### ISSUE TITLE
[Question] Is it possible to use a different authentication mechanism per secret?

### ISSUE THREAD

**Issue by erick-thompson** [SparebankenVest/azure-key-vault-to-kubernetes#94]
I am using the default authentication, but there are some Key Vaults that I would like to access with an explicit id/password. Does akv2k8s support multiple authentication mechanisms, or only one per deployment (of akv2k8s)?

**Comment by gaurav-magassian** [comment]
This is very unlikely as per CDR definition at https://akv2k8s.io/reference/azure-key-vault-secret/

It does not give any place where one can supply an akv username and password

**Comment by erick-thompson** [comment]
Is there any consideration of allowing this? 

The scenario is that I am trying to achieve AKS independence, and so using something like AKS pod identity isn't feasible. Having the ability to mix and match authentication methods would give more flexibility.

**Comment by torresdal** [comment]
We've thought about implementing the operator pattern for akv2k8s, which would allow what you want as well as supporting multi tenants. Currently it's not supported.
